#ifndef __CLOCK_SERIAL_HUB_H__
#define __CLOCK_SERIAL_HUB_H__


/*
// 操作寄存器
name	有效电平	位
UNUSED		0
UNUSED		1
UNUSED		2
UNUSED		3
UNUSED		4
UNUSED		5
TRIPWIRE_TEST	高	6
THERMO_LO_TEST	高	7
THERMO_HI_TEST	高	8
HG3_FIX		9
HG2_FIX		10
HG1_FIX		11
HG0_FIX		12
FUSE1_BROKE_TEST	高	13
FUSE0_BROKE_TEST	高	14
FUSE1_SHORT_TEST	高	15
FUSE0_SHORT_TEST	高	16
FUSE1_TRIGGER	高	17
FUSE0_TRIGGER	高	18
TRIPWIRE_EN	高	19
THERMO_EN	高	20
GYRO_EN	高	21
HG_EN	高	22
FUSE_EN	高	23
*/

enum serial_hub_crl_bits{
  SERIAL_BIT_UNUSED0 = 0,
  SERIAL_BIT_UNUSED1 = 1,
  SERIAL_BIT_UNUSED2 = 2,
  SERIAL_BIT_UNUSED3 = 3,
  SERIAL_BIT_UNUSED4 = 4,
  SERIAL_BIT_UNUSED5 = 5,
  SERIAL_BIT_TRIPWIRE_TEST = 6,
  SERIAL_BIT_THERMO_LO_TEST = 7,
  SERIAL_BIT_THERMO_HI_TEST = 8,
  SERIAL_BIT_HG3_FIX = 9,
  SERIAL_BIT_HG2_FIX = 10,
  SERIAL_BIT_HG1_FIX = 11,
  SERIAL_BIT_HG0_FIX = 12,
  SERIAL_BIT_FUSE1_BROKE_TEST = 13,
  SERIAL_BIT_FUSE0_BROKE_TEST = 14,
  SERIAL_BIT_FUSE1_SHORT_TEST = 15,
  SERIAL_BIT_FUSE0_SHORT_TEST = 16,
  SERIAL_BIT_FUSE1_TRIGGER = 17,
  SERIAL_BIT_FUSE0_TRIGGER = 18,
  SERIAL_BIT_TRIPWIRE_EN = 19,
  SERIAL_BIT_THERMO_EN = 20,
  SERIAL_BIT_GYRO_EN = 21,
  SERIAL_BIT_HG_EN = 22,
  SERIAL_BIT_FUSE_EN = 23,
};

/*
// 状态寄存器
name	有效电平	位
name	有效电平	位
UNUSED	低	0
RTC_HIT	低	1
FUSE1_TRIGGER	低	2
FUSE0_TRIGGER	低	3
TRIPWIRE_HIT	低	4
HG3_HIT	低	5
HG2_HIT	低	6
HG1_HIT	低	7
HG0_HIT	低	8
THERMO_LO_HIT	低	9
THERMO_HI_HIT	低	10
GYRO_HIT	低	11
FUSE1_BROKE	低	12
FUSE0_BROKE	低	13
FUSE1_SHORT	低	14
FUSE0_SHORT	低	15
*/

enum serial_hub_state_bits{
  SERIAL_BIT_UNUSED6 = 0,
  SERIAL_BIT_RTC_HIT = 1,
  SERIAL_BIT_FUSE1_TRIGGERED = 2,
  SERIAL_BIT_FUSE0_TRIGGERED = 3,
  SERIAL_BIT_TRIPWIRE_HIT = 4,
  SERIAL_BIT_HG3_HIT = 5,
  SERIAL_BIT_HG2_HIT = 6,
  SERIAL_BIT_HG1_HIT = 7,
  SERIAL_BIT_HG0_HIT = 8,
  SERIAL_BIT_THERMO_LO_HIT = 9,
  SERIAL_BIT_THERMO_HI_HIT = 10,
  SERIAL_BIT_GYRO_HIT = 11,
  SERIAL_BIT_FUSE1_BROKE = 12,
  SERIAL_BIT_FUSE0_BROKE = 13,
  SERIAL_BIT_FUSE1_SHORT = 14,
  SERIAL_BIT_FUSE0_SHORT = 15,
};

void serial_hub_initialize(void);
void serial_ctl_out(void);
void serial_state_in(void);
void serial_set_ctl_bit(unsigned char index, bit what);
bit serial_test_ctl_bit(unsigned char index);
bit serial_test_state_bit(unsigned char index);

#endif