#ifndef __CLOCK_SERIAL_HUB_H__
#define __CLOCK_SERIAL_HUB_H__


enum serial_hub_crl_bits{
  SERIAL_BIT_C_UNUSED0 = 0,
  SERIAL_BIT_C_UNUSED1 = 1,
  SERIAL_BIT_C_UNUSED2 = 2,
  SERIAL_BIT_C_UNUSED3 = 3,
  SERIAL_BIT_C_UNUSED4 = 4,
  SERIAL_BIT_C_UNUSED5 = 5,
  SERIAL_BIT_TRIPWIRE_TEST  = 6,
  SERIAL_BIT_THERMO_LO_TEST = 7,
  SERIAL_BIT_THERMO_HI_TEST = 8,
  SERIAL_BIT_FUSE1_SHORT_TEST = 9,
  SERIAL_BIT_FUSE1_BROKE_TEST = 10,
  SERIAL_BIT_FUSE0_SHORT_TEST = 11,
  SERIAL_BIT_FUSE0_BROKE_TEST = 12,
  SERIAL_BIT_HG3_FIX = 13,
  SERIAL_BIT_HG2_FIX = 14,
  SERIAL_BIT_HG1_FIX = 15,
  SERIAL_BIT_HG0_FIX = 16,
  SERIAL_BIT_FUSE1_TRIGGER = 17,
  SERIAL_BIT_FUSE0_TRIGGER = 18,
  SERIAL_BIT_TRIPWIRE_EN = 19,
  SERIAL_BIT_THERMO_EN = 20,
  SERIAL_BIT_GYRO_EN = 21,
  SERIAL_BIT_HG_EN = 22,
  SERIAL_BIT_FUSE_EN = 23,
};


enum serial_hub_state_bits{
  SERIAL_BIT_S_UNUSED0 = 0,
  SERIAL_BIT_RTC_HIT = 1,
  SERIAL_BIT_FUSE1_TRIGGERED = 2,
  SERIAL_BIT_FUSE0_TRIGGERED = 3,
  SERIAL_BIT_TRIPWIRE_HIT = 4,
  SERIAL_BIT_HG3_HIT = 5,
  SERIAL_BIT_HG2_HIT = 6,
  SERIAL_BIT_HG1_HIT = 7,
  SERIAL_BIT_HG0_HIT = 8,
  SERIAL_BIT_THERMO_LO_HIT = 9,
  SERIAL_BIT_THERMO_HI_HIT = 10,
  SERIAL_BIT_GYRO_HIT = 11,
  SERIAL_BIT_FUSE1_BROKE = 12,
  SERIAL_BIT_FUSE0_BROKE = 13,
  SERIAL_BIT_FUSE1_SHORT = 14,
  SERIAL_BIT_FUSE0_SHORT = 15,
};

void serial_hub_initialize(void);
void serial_ctl_out(void);
void serial_state_in(void);
void serial_set_ctl_bit(unsigned char index, bit what);
bit serial_test_ctl_bit(unsigned char index);
bit serial_test_state_bit(unsigned char index);

#endif