#include "sm.h"
#include "debug.h"
#include "led.h"
#include "beeper.h"
#include "alarm.h"
#include "lt_timer.h"

/* state machine */
#include "sm_clock_display.h"
#include "sm_clock_mod_time.h"
#include "sm_clock_mod_alarm.h"
#include "sm_clock_mod_global_flag.h"
#include "sm_clock_powersave.h"
#include "sm_clock_counter.h"
#include "sm_clock_timer.h"
#include "sm_clock_alarm.h"


#include "sm_fuse_mode.h"
#include "sm_fuse_test.h"
#include "sm_fuse_param.h"
#include "sm_fuse_timer.h"
#include "sm_fuse_grenade.h"
#include "sm_fuse_detonate.h"
#include "sm_fuse_powersave.h"

// state machine translate defines
// 超级复杂变态
static const struct sm_trans code sm_trans_clock_display[] = 
{
  /* SM_CLOCK_DISPLAY */
  // 从别的状态切过来，防止误操作
  {SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_INIT, EV_KEY_MOD_UP, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_HHMMSS, sm_clock_display},  
  // 按mod0显示年月日
  {SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_HHMMSS, EV_KEY_MOD_PRESS, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_YYMMDD, sm_clock_display},
  // 每250ms读取下rtc
  {SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_HHMMSS, EV_250MS, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_HHMMSS, sm_clock_display},
  // 按mod1进入修改时间模式
  {SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_HHMMSS, EV_KEY_MOD_LPRESS, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_INIT, sm_clock_mod_time},
  // 闹钟0响了
  {SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_HHMMSS, EV_ALARM0, SM_CLOCK_ALARM<<4|SM_CLOCK_ALARM_HIT_ALARM0, sm_clock_alarm},
  // 闹钟1响了
  {SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_HHMMSS, EV_ALARM1, SM_CLOCK_ALARM<<4|SM_CLOCK_ALARM_HIT_ALARM1, sm_clock_alarm},
  // 该进入节电模式了
  {SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_HHMMSS, EV_POWER_SAVE, SM_CLOCK_POWERSAVE<<4|SM_CLOCK_POWERSAVE_INIT, sm_clock_powersave},
  // 进入跑表功能
  {SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_HHMMSS, EV_KEY_SET_LPRESS, SM_CLOCK_TIMER<<4|SM_CLOCK_TIMER_INIT, sm_clock_timer},

  // 按modset1进入fuse功能集合
  {SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_HHMMSS, EV_KEY_MOD_SET_LPRESS, SM_FUSE_TEST<<4|SM_FUSE_TEST_INIT, sm_fuse_test},

  // 按mod0显示星期几
  {SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_YYMMDD, EV_KEY_MOD_PRESS, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_WEEK, sm_clock_display},
  // 每1s读一下rtc
  {SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_YYMMDD, EV_1S, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_YYMMDD, sm_clock_display},
  // set0回到时分秒显示模式
  {SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_YYMMDD, EV_KEY_SET_PRESS, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_HHMMSS, sm_clock_display},
  
  // 按mod0显示温度
  {SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_WEEK, EV_KEY_MOD_PRESS, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_TEMP, sm_clock_display},
  // 每1s读一下rtc
  {SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_WEEK, EV_1S, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_WEEK, sm_clock_display},
  // set0回到时分秒显示模式
  {SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_WEEK, EV_KEY_SET_PRESS, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_HHMMSS, sm_clock_display},
  
  // 按mod0回到时分秒显示模式
  {SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_TEMP, EV_KEY_MOD_PRESS, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_HHMMSS, sm_clock_display},
  // 每1s读一下rtc
  {SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_TEMP, EV_1S, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_TEMP, sm_clock_display},
  // set0回到时分秒显示模式
  {SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_TEMP, EV_KEY_SET_PRESS, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_HHMMSS, sm_clock_display},
};

static const struct sm_trans code sm_trans_clock_mod_time[] = {
  /* SM_CLOCK_MODIFY_TIME */
  // 从别的状态进入，防止误操作
  {SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_INIT, EV_KEY_MOD_UP, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_HH, sm_clock_mod_time}, 
  // 按mod0进入修改分钟模式
  {SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_HH, EV_KEY_MOD_PRESS, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_MM, sm_clock_mod_time},
  // 按set0小时++并写入rtc
  {SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_HH, EV_KEY_SET_PRESS, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_HH, sm_clock_mod_time},
  // set1小时连续++
  {SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_HH, EV_KEY_SET_LPRESS, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_HH, sm_clock_mod_time},
  // set抬起停止++并写入rtc
  {SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_HH, EV_KEY_SET_UP, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_HH, sm_clock_mod_time},
  // 每250ms读一次rtc
  {SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_HH, EV_250MS, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_HH, sm_clock_mod_time},
  // mod1 进入修改闹钟模式
  {SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_HH, EV_KEY_MOD_LPRESS, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_INIT, sm_clock_mod_alarm},
  // mod0 进入修改秒模式
  {SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_MM, EV_KEY_MOD_PRESS, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_SS, sm_clock_mod_time},
  // set0 分钟++并写入rtc
  {SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_MM, EV_KEY_SET_PRESS, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_MM, sm_clock_mod_time},
  // set1 分钟持续++
  {SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_MM, EV_KEY_SET_LPRESS, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_MM, sm_clock_mod_time},
  // set抬起停止++并写入rtc
  {SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_MM, EV_KEY_SET_UP, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_MM, sm_clock_mod_time},
  // 每250ms读一下rtc
  {SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_MM, EV_250MS, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_MM, sm_clock_mod_time}, 
  // mod1 进入修改闹钟模式
  {SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_MM, EV_KEY_MOD_LPRESS, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_INIT, sm_clock_mod_alarm},
  // mod0进入修改年模式
  {SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_SS, EV_KEY_MOD_PRESS, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_YY, sm_clock_mod_time},
  // set0将秒清0并写入rtc
  {SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_SS, EV_KEY_SET_PRESS, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_SS, sm_clock_mod_time},
  // 每250ms读一次rtc 
  {SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_SS, EV_250MS, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_SS, sm_clock_mod_time},
  // mod1进入修改闹钟模式
  {SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_SS, EV_KEY_MOD_LPRESS, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_INIT, sm_clock_mod_alarm},  
  // 按mod0进入修改月模式
  {SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_YY, EV_KEY_MOD_PRESS, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_MO, sm_clock_mod_time},
  // set0 年++
  {SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_YY, EV_KEY_SET_PRESS, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_YY, sm_clock_mod_time},
  // 长按set年持续++
  {SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_YY, EV_KEY_SET_LPRESS, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_YY, sm_clock_mod_time},
  // 抬起set停止年++并写入rtc
  {SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_YY, EV_KEY_SET_UP, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_YY, sm_clock_mod_time},
  // 每250ms读取一次rtc  
  {SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_YY, EV_250MS, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_YY, sm_clock_mod_time},
  // mod1 进入修改闹钟模式  
  {SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_YY, EV_KEY_MOD_LPRESS, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_INIT, sm_clock_mod_alarm}, 
  // mod0 进入修改日模式
  {SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_MO, EV_KEY_MOD_PRESS, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_DD, sm_clock_mod_time},
  // set0 月++
  {SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_MO, EV_KEY_SET_PRESS, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_MO, sm_clock_mod_time},
  // 长按set 月持续++
  {SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_MO, EV_KEY_SET_LPRESS, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_MO, sm_clock_mod_time}, 
  // 抬起set停止月++并写入rtc
  {SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_MO, EV_KEY_SET_UP, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_MO, sm_clock_mod_time}, 
  // 每250ms读取一下rtc
  {SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_MO, EV_250MS, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_MO, sm_clock_mod_time},
  // mod1 进入修改闹钟模式  
  {SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_MO, EV_KEY_MOD_LPRESS, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_INIT, sm_clock_mod_alarm},   
  // mod0 进入修改小时模式
  {SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_DD, EV_KEY_MOD_PRESS, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_HH, sm_clock_mod_time},
  // set0 日++
  {SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_DD, EV_KEY_SET_PRESS, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_DD, sm_clock_mod_time},
  // set1 日持续++  
  {SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_DD, EV_KEY_SET_LPRESS, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_DD, sm_clock_mod_time},
  // set抬起停止日++写入rtc  
  {SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_DD, EV_KEY_SET_UP, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_DD, sm_clock_mod_time},
  // 每250ms读取一下rtc
  {SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_DD, EV_250MS, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_DD, sm_clock_mod_time}, 
  // mod1 进入修改闹钟模式
  {SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_DD, EV_KEY_MOD_LPRESS, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_INIT, sm_clock_mod_alarm},
};

static const struct sm_trans code sm_trans_clock_mod_alarm[] = {
  /* SM_CLOCK_MODIFY_ALARM */
  // 从别的状态进入，防止误操作
  {SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_INIT, EV_KEY_MOD_UP, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_HH, sm_clock_mod_alarm},
  // set0小时++  
  {SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_HH, EV_KEY_SET_PRESS, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_HH, sm_clock_mod_alarm},
  // set1小时持续++
  {SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_HH, EV_KEY_SET_LPRESS, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_HH, sm_clock_mod_alarm},
  // set抬起停止++，写入rtc
  {SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_HH, EV_KEY_SET_UP, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_HH, sm_clock_mod_alarm},
  // mod0进入修改分钟模式
  {SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_HH, EV_KEY_MOD_PRESS, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_MM, sm_clock_mod_alarm},
  // mod1进入修改全局状态模式
  {SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_HH, EV_KEY_MOD_LPRESS, SM_CLOCK_MODIFY_GLOBAL_FLAG<<4|SM_CLOCK_MODIFY_GLOBAL_FLAG_INIT, sm_clock_mod_global_flag},
  
  // set0分钟++
  {SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_MM, EV_KEY_SET_PRESS, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_MM, sm_clock_mod_alarm},
  // set1分钟持续++
  {SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_MM, EV_KEY_SET_LPRESS, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_MM, sm_clock_mod_alarm}, 
  // set抬起停止++，写入rtc  
  {SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_MM, EV_KEY_SET_UP, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_MM, sm_clock_mod_alarm}, 
  // mod0进入调整重复日状态
  {SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_MM, EV_KEY_MOD_PRESS, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_DAY1, sm_clock_mod_alarm}, 
  // mod1进入修改全局状态模式  
  {SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_MM, EV_KEY_MOD_LPRESS, SM_CLOCK_MODIFY_GLOBAL_FLAG<<4|SM_CLOCK_MODIFY_GLOBAL_FLAG_INIT, sm_clock_mod_global_flag},
 

  // set0调整打开关闭，并写入rtc
  {SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_DAY1, EV_KEY_SET_PRESS, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_DAY1, sm_clock_mod_alarm},
  // mod0进入修改下一天状态
  {SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_DAY1, EV_KEY_MOD_PRESS, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_DAY2, sm_clock_mod_alarm}, 
  // mod1进入修改全局状态模式  
  {SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_DAY1, EV_KEY_MOD_LPRESS, SM_CLOCK_MODIFY_GLOBAL_FLAG<<4|SM_CLOCK_MODIFY_GLOBAL_FLAG_INIT, sm_clock_mod_global_flag},

  // set0调整打开关闭，并写入rtc
  {SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_DAY2, EV_KEY_SET_PRESS, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_DAY2, sm_clock_mod_alarm},
  // mod0进入修改下一天状态
  {SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_DAY2, EV_KEY_MOD_PRESS, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_DAY3, sm_clock_mod_alarm}, 
  // mod1进入修改全局状态模式  
  {SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_DAY2, EV_KEY_MOD_LPRESS, SM_CLOCK_MODIFY_GLOBAL_FLAG<<4|SM_CLOCK_MODIFY_GLOBAL_FLAG_INIT, sm_clock_mod_global_flag},

  // set0调整打开关闭，并写入rtc
  {SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_DAY3, EV_KEY_SET_PRESS, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_DAY3, sm_clock_mod_alarm},
  // mod0进入修改下一天状态
  {SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_DAY3, EV_KEY_MOD_PRESS, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_DAY4, sm_clock_mod_alarm}, 
  // mod1进入修改全局状态模式  
  {SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_DAY3, EV_KEY_MOD_LPRESS, SM_CLOCK_MODIFY_GLOBAL_FLAG<<4|SM_CLOCK_MODIFY_GLOBAL_FLAG_INIT, sm_clock_mod_global_flag},

  // set0调整打开关闭，并写入rtc
  {SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_DAY4, EV_KEY_SET_PRESS, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_DAY4, sm_clock_mod_alarm},
  // mod0进入修改下一天状态
  {SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_DAY4, EV_KEY_MOD_PRESS, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_DAY5, sm_clock_mod_alarm}, 
  // mod1进入修改全局状态模式  
  {SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_DAY4, EV_KEY_MOD_LPRESS, SM_CLOCK_MODIFY_GLOBAL_FLAG<<4|SM_CLOCK_MODIFY_GLOBAL_FLAG_INIT, sm_clock_mod_global_flag},

  // set0调整打开关闭，并写入rtc
  {SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_DAY5, EV_KEY_SET_PRESS, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_DAY5, sm_clock_mod_alarm},
  // mod0进入修改下一天状态
  {SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_DAY5, EV_KEY_MOD_PRESS, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_DAY6, sm_clock_mod_alarm}, 
  // mod1进入修改全局状态模式  
  {SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_DAY5, EV_KEY_MOD_LPRESS, SM_CLOCK_MODIFY_GLOBAL_FLAG<<4|SM_CLOCK_MODIFY_GLOBAL_FLAG_INIT, sm_clock_mod_global_flag},

  // set0调整打开关闭，并写入rtc
  {SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_DAY6, EV_KEY_SET_PRESS, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_DAY6, sm_clock_mod_alarm},
  // mod0进入修改下一天状态
  {SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_DAY6, EV_KEY_MOD_PRESS, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_DAY7, sm_clock_mod_alarm}, 
  // mod1进入修改全局状态模式  
  {SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_DAY6, EV_KEY_MOD_LPRESS, SM_CLOCK_MODIFY_GLOBAL_FLAG<<4|SM_CLOCK_MODIFY_GLOBAL_FLAG_INIT, sm_clock_mod_global_flag},

  // set0调整打开关闭，并写入rtc
  {SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_DAY7, EV_KEY_SET_PRESS, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_DAY7, sm_clock_mod_alarm},
  // mod0回到调整闹钟小时状态
  {SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_DAY7, EV_KEY_MOD_PRESS, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_HH, sm_clock_mod_alarm}, 
  // mod1进入修改全局状态模式  
  {SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_DAY7, EV_KEY_MOD_LPRESS, SM_CLOCK_MODIFY_GLOBAL_FLAG<<4|SM_CLOCK_MODIFY_GLOBAL_FLAG_INIT, sm_clock_mod_global_flag},  
};

static const struct sm_trans code sm_trans_clock_mod_global_flag[] = {
  /* SM_CLOCK_MODIFY_GLOBAL_FLAG */
  // 防止误操作
  {SM_CLOCK_MODIFY_GLOBAL_FLAG<<4|SM_CLOCK_MODIFY_GLOBAL_FLAG_INIT, EV_KEY_MOD_UP, SM_CLOCK_MODIFY_GLOBAL_FLAG<<4|SM_CLOCK_MODIFY_GLOBAL_FLAG_PS, sm_clock_mod_global_flag},
  // set0 省电模式超时时间设置
  {SM_CLOCK_MODIFY_GLOBAL_FLAG<<4|SM_CLOCK_MODIFY_GLOBAL_FLAG_PS, EV_KEY_SET_PRESS, SM_CLOCK_MODIFY_GLOBAL_FLAG<<4|SM_CLOCK_MODIFY_GLOBAL_FLAG_PS, sm_clock_mod_global_flag},
  // mod0 进入设置整点报时on/off状态
  {SM_CLOCK_MODIFY_GLOBAL_FLAG<<4|SM_CLOCK_MODIFY_GLOBAL_FLAG_PS, EV_KEY_MOD_PRESS, SM_CLOCK_MODIFY_GLOBAL_FLAG<<4|SM_CLOCK_MODIFY_GLOBAL_FLAG_BS, sm_clock_mod_global_flag},  
  // mod1进入显示时间状态
  {SM_CLOCK_MODIFY_GLOBAL_FLAG<<4|SM_CLOCK_MODIFY_GLOBAL_FLAG_PS, EV_KEY_MOD_LPRESS, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_INIT, sm_clock_display},
  // set0 整点报时on/off
  {SM_CLOCK_MODIFY_GLOBAL_FLAG<<4|SM_CLOCK_MODIFY_GLOBAL_FLAG_BS, EV_KEY_SET_PRESS, SM_CLOCK_MODIFY_GLOBAL_FLAG<<4|SM_CLOCK_MODIFY_GLOBAL_FLAG_BS, sm_clock_mod_global_flag},
  // mod0 进入闹铃音乐选择
  {SM_CLOCK_MODIFY_GLOBAL_FLAG<<4|SM_CLOCK_MODIFY_GLOBAL_FLAG_BS, EV_KEY_MOD_PRESS, SM_CLOCK_MODIFY_GLOBAL_FLAG<<4|SM_CLOCK_MODIFY_GLOBAL_FLAG_ALARM_MUSIC, sm_clock_mod_global_flag},
  // mod1进入显示时间状态
  {SM_CLOCK_MODIFY_GLOBAL_FLAG<<4|SM_CLOCK_MODIFY_GLOBAL_FLAG_BS, EV_KEY_MOD_LPRESS, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_INIT, sm_clock_display}, 
  // set0 闹铃音乐设置
  {SM_CLOCK_MODIFY_GLOBAL_FLAG<<4|SM_CLOCK_MODIFY_GLOBAL_FLAG_ALARM_MUSIC, EV_KEY_SET_PRESS, SM_CLOCK_MODIFY_GLOBAL_FLAG<<4|SM_CLOCK_MODIFY_GLOBAL_FLAG_ALARM_MUSIC, sm_clock_mod_global_flag},
  // mod0 进入1按键音设置
  {SM_CLOCK_MODIFY_GLOBAL_FLAG<<4|SM_CLOCK_MODIFY_GLOBAL_FLAG_ALARM_MUSIC, EV_KEY_MOD_PRESS, SM_CLOCK_MODIFY_GLOBAL_FLAG<<4|SM_CLOCK_MODIFY_GLOBAL_FLAG_BEEP, sm_clock_mod_global_flag}, 
  // mod1进入显示时间状态
  {SM_CLOCK_MODIFY_GLOBAL_FLAG<<4|SM_CLOCK_MODIFY_GLOBAL_FLAG_ALARM_MUSIC, EV_KEY_MOD_LPRESS, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_INIT, sm_clock_display}, 
  // set0 打开关闭按键音
  {SM_CLOCK_MODIFY_GLOBAL_FLAG<<4|SM_CLOCK_MODIFY_GLOBAL_FLAG_BEEP, EV_KEY_SET_PRESS, SM_CLOCK_MODIFY_GLOBAL_FLAG<<4|SM_CLOCK_MODIFY_GLOBAL_FLAG_BEEP, sm_clock_mod_global_flag},
  // mod0 进入1224小时设置状态
  {SM_CLOCK_MODIFY_GLOBAL_FLAG<<4|SM_CLOCK_MODIFY_GLOBAL_FLAG_BEEP, EV_KEY_MOD_PRESS, SM_CLOCK_MODIFY_GLOBAL_FLAG<<4|SM_CLOCK_MODIFY_GLOBAL_FLAG_1224, sm_clock_mod_global_flag}, 
  // mod1进入显示时间状态
  {SM_CLOCK_MODIFY_GLOBAL_FLAG<<4|SM_CLOCK_MODIFY_GLOBAL_FLAG_BEEP, EV_KEY_MOD_LPRESS, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_INIT, sm_clock_display}, 
  // set0 1224模式切换
  {SM_CLOCK_MODIFY_GLOBAL_FLAG<<4|SM_CLOCK_MODIFY_GLOBAL_FLAG_1224, EV_KEY_SET_PRESS, SM_CLOCK_MODIFY_GLOBAL_FLAG<<4|SM_CLOCK_MODIFY_GLOBAL_FLAG_1224, sm_clock_mod_global_flag},
  // mod0 进入设置省电模式状态
  {SM_CLOCK_MODIFY_GLOBAL_FLAG<<4|SM_CLOCK_MODIFY_GLOBAL_FLAG_1224, EV_KEY_MOD_PRESS, SM_CLOCK_MODIFY_GLOBAL_FLAG<<4|SM_CLOCK_MODIFY_GLOBAL_FLAG_PS, sm_clock_mod_global_flag}, 
  // mod1 进入显示时间状态
  {SM_CLOCK_MODIFY_GLOBAL_FLAG<<4|SM_CLOCK_MODIFY_GLOBAL_FLAG_1224, EV_KEY_MOD_LPRESS, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_HHMMSS, sm_clock_display},
};
  
static const struct sm_trans code sm_trans_clock_powersave[] = {
  /* SM_CLOCK_POWERSAVE */
  // 250ms后进入睡眠
  {SM_CLOCK_POWERSAVE<<4|SM_CLOCK_POWERSAVE_INIT, EV_250MS, SM_CLOCK_POWERSAVE<<4|SM_CLOCK_POWERSAVE_PS, sm_clock_powersave},
  // mod0回到时间显示模式 
  {SM_CLOCK_POWERSAVE<<4|SM_CLOCK_POWERSAVE_PS, EV_KEY_MOD_PRESS, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_HHMMSS, sm_clock_display},
  // set0回到时间显示模式
  {SM_CLOCK_POWERSAVE<<4|SM_CLOCK_POWERSAVE_PS, EV_KEY_SET_PRESS, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_HHMMSS, sm_clock_display},
  // 闹铃响了，唤醒吧
  {SM_CLOCK_POWERSAVE<<4|SM_CLOCK_POWERSAVE_PS, EV_ALARM0, SM_CLOCK_ALARM<<4|SM_CLOCK_ALARM_HIT_ALARM0, sm_clock_alarm},
  {SM_CLOCK_POWERSAVE<<4|SM_CLOCK_POWERSAVE_PS, EV_ALARM1, SM_CLOCK_ALARM<<4|SM_CLOCK_ALARM_HIT_ALARM1, sm_clock_alarm},
};  

static const struct sm_trans code sm_trans_clock_alarm[] = {  
  /* SM_CLOCK_ALARM */
  // mod0回到时间显示模式
  {SM_CLOCK_ALARM<<4|SM_CLOCK_ALARM_HIT_ALARM0, EV_KEY_MOD_PRESS, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_HHMMSS, sm_clock_display},
  // set0回到时间显示模式
  {SM_CLOCK_ALARM<<4|SM_CLOCK_ALARM_HIT_ALARM0, EV_KEY_SET_PRESS, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_HHMMSS, sm_clock_display}, 
  // mod0回到时间显示模式
  {SM_CLOCK_ALARM<<4|SM_CLOCK_ALARM_HIT_ALARM1, EV_KEY_MOD_PRESS, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_HHMMSS, sm_clock_display},
  // set0回到时间显示模式
  {SM_CLOCK_ALARM<<4|SM_CLOCK_ALARM_HIT_ALARM1, EV_KEY_SET_PRESS, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_HHMMSS, sm_clock_display}, 
};

static const struct sm_trans code sm_trans_clock_timer[] = {  
  /* SM_CLOCK_TIMER */
  // 防止误操作
  {SM_CLOCK_TIMER<<4|SM_CLOCK_TIMER_INIT, EV_KEY_SET_UP, SM_CLOCK_TIMER<<4|SM_CLOCK_TIMER_CLEAR, sm_clock_timer},
  // set1进入倒计时器模式
  {SM_CLOCK_TIMER<<4|SM_CLOCK_TIMER_CLEAR, EV_KEY_SET_LPRESS, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_INIT, sm_clock_counter},
  // mod0跑表开始跑
  {SM_CLOCK_TIMER<<4|SM_CLOCK_TIMER_CLEAR, EV_KEY_MOD_DOWN, SM_CLOCK_TIMER<<4|SM_CLOCK_TIMER_RUNNING, sm_clock_timer}, 
  // set0计次
  {SM_CLOCK_TIMER<<4|SM_CLOCK_TIMER_RUNNING, EV_KEY_SET_DOWN, SM_CLOCK_TIMER<<4|SM_CLOCK_TIMER_RUNNING, sm_clock_timer},
  {SM_CLOCK_TIMER<<4|SM_CLOCK_TIMER_RUNNING, EV_KEY_SET_UP, SM_CLOCK_TIMER<<4|SM_CLOCK_TIMER_RUNNING, sm_clock_timer},  
  // mod0跑表停止  
  {SM_CLOCK_TIMER<<4|SM_CLOCK_TIMER_RUNNING, EV_KEY_MOD_DOWN, SM_CLOCK_TIMER<<4|SM_CLOCK_TIMER_STOP, sm_clock_timer},
  // mod0跑表清零
  {SM_CLOCK_TIMER<<4|SM_CLOCK_TIMER_STOP, EV_KEY_MOD_DOWN, SM_CLOCK_TIMER<<4|SM_CLOCK_TIMER_CLEAR, sm_clock_timer},
  // set0逐次显示计次
  {SM_CLOCK_TIMER<<4|SM_CLOCK_TIMER_STOP, EV_KEY_SET_DOWN, SM_CLOCK_TIMER<<4|SM_CLOCK_TIMER_STOP, sm_clock_timer},
  {SM_CLOCK_TIMER<<4|SM_CLOCK_TIMER_STOP, EV_KEY_SET_UP, SM_CLOCK_TIMER<<4|SM_CLOCK_TIMER_STOP, sm_clock_timer},  
};  

static const struct sm_trans code sm_trans_clock_counter[] = {  
  /* SM_CLOCK_COUNTER */
  // 防止误操作
  {SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_INIT, EV_KEY_SET_UP, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_HH, sm_clock_counter},
  // mod0进入修改分钟状态
  {SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_HH, EV_KEY_MOD_PRESS, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_MM, sm_clock_counter},
  // set0小时++
  {SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_HH, EV_KEY_SET_PRESS, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_HH, sm_clock_counter},
  // set1小时快速++
  {SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_HH, EV_KEY_SET_LPRESS, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_HH, sm_clock_counter}, 
  // set抬起小时快速++停止
  {SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_HH, EV_KEY_SET_UP, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_HH, sm_clock_counter},   
  // mod1切回时间显示
  {SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_HH, EV_KEY_MOD_LPRESS, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_INIT, sm_clock_display},
  // 每250ms刷新显示
  {SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_HH, EV_250MS, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_HH, sm_clock_counter},
  // mod0进入修改秒状态
  {SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_MM, EV_KEY_MOD_PRESS, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_SS, sm_clock_counter},
  // set0 分钟++
  {SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_MM, EV_KEY_SET_PRESS, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_MM, sm_clock_counter},
  // set1 分钟快速++
  {SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_MM, EV_KEY_SET_LPRESS, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_MM, sm_clock_counter},
  // set 抬起分钟快速++停止  
  {SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_MM, EV_KEY_SET_UP, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_MM, sm_clock_counter},
  // mod1 回到时间显示  
  {SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_MM, EV_KEY_MOD_LPRESS, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_INIT, sm_clock_display},  
  // 每250ms刷新显示
  {SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_MM, EV_250MS, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_MM, sm_clock_counter},
  // mod0 开始倒计时
  {SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_SS, EV_KEY_MOD_PRESS, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_RUNNING, sm_clock_counter},
  // set0 秒++
  {SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_SS, EV_KEY_SET_PRESS, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_SS, sm_clock_counter},
  // set1 秒快速++
  {SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_SS, EV_KEY_SET_LPRESS, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_SS, sm_clock_counter},
  // set抬起秒快速++停止
  {SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_SS, EV_KEY_SET_UP, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_SS, sm_clock_counter},
  // mod1回到时间显示  
  {SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_SS, EV_KEY_MOD_LPRESS, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_INIT, sm_clock_display},
  // 每250ms刷新显示
  {SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_SS, EV_250MS, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_SS, sm_clock_counter},
  // set0 暂停倒计时
  {SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_RUNNING, EV_KEY_SET_PRESS, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_PAUSE, sm_clock_counter}, 
  // set0 继续倒计时
  {SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_PAUSE, EV_KEY_SET_PRESS, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_RUNNING, sm_clock_counter},
  // mod0 清除
  {SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_PAUSE, EV_KEY_MOD_PRESS, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_HH, sm_clock_counter},
  // 倒计时结束，响铃
  {SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_RUNNING, EV_COUNTER, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_STOP, sm_clock_counter},
  // mod0 停止响铃
  {SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_STOP, EV_KEY_MOD_PRESS, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_HH, sm_clock_counter},  
};


static const struct sm_trans code sm_trans_fuse_test[] = {  
  /* SM_FUSE_TEST */
  {SM_FUSE_TEST<<4|SM_FUSE_TEST_INIT, EV_1S, SM_FUSE_TEST<<4|SM_FUSE_TEST_INIT, sm_fuse_test},
  {SM_FUSE_TEST<<4|SM_FUSE_TEST_INIT, EV_KEY_MOD_PRESS, SM_FUSE_TEST<<4|SM_FUSE_TEST_INIT, sm_fuse_test},
  {SM_FUSE_TEST<<4|SM_FUSE_TEST_INIT, EV_KEY_SET_PRESS, SM_FUSE_TEST<<4|SM_FUSE_TEST_INIT, sm_fuse_test},	
  {SM_FUSE_TEST<<4|SM_FUSE_TEST_INIT, EV_FUSE_SEL0, SM_FUSE_TEST<<4|SM_FUSE_TEST_FUSE0_SHORT, sm_fuse_test},
  // set0启动测试
  {SM_FUSE_TEST<<4|SM_FUSE_TEST_FUSE0_SHORT, EV_KEY_SET_PRESS, SM_FUSE_TEST<<4|SM_FUSE_TEST_FUSE0_SHORT, sm_fuse_test},
  // 测试fuse0 short 收到EV_FUSE0_SHORT, 更新显示
  {SM_FUSE_TEST<<4|SM_FUSE_TEST_FUSE0_SHORT, EV_FUSE0_SHORT, SM_FUSE_TEST<<4|SM_FUSE_TEST_FUSE0_SHORT, sm_fuse_test},
  // 测试fuse0 short 收到EV_1S, 更新显示
  {SM_FUSE_TEST<<4|SM_FUSE_TEST_FUSE0_SHORT, EV_1S, SM_FUSE_TEST<<4|SM_FUSE_TEST_FUSE0_SHORT, sm_fuse_test},
  // mod0 切换到测试fuse0 broke
  {SM_FUSE_TEST<<4|SM_FUSE_TEST_FUSE0_SHORT, EV_KEY_MOD_PRESS, SM_FUSE_TEST<<4|SM_FUSE_TEST_FUSE0_BROKE, sm_fuse_test},
  // mod1 切换回时钟模式
  {SM_FUSE_TEST<<4|SM_FUSE_TEST_FUSE0_SHORT, EV_KEY_MOD_LPRESS, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_INIT, sm_clock_display},
  // set1 切换到参数设置
  {SM_FUSE_TEST<<4|SM_FUSE_TEST_FUSE0_SHORT, EV_KEY_SET_LPRESS, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_INIT, sm_fuse_param},

  // set0启动测试
  {SM_FUSE_TEST<<4|SM_FUSE_TEST_FUSE0_BROKE, EV_KEY_SET_PRESS, SM_FUSE_TEST<<4|SM_FUSE_TEST_FUSE0_BROKE, sm_fuse_test},
  // 测试fuse0 broke 收到EV_FUSE0_BROKE, 更新显示
  {SM_FUSE_TEST<<4|SM_FUSE_TEST_FUSE0_BROKE, EV_FUSE0_BROKE, SM_FUSE_TEST<<4|SM_FUSE_TEST_FUSE0_BROKE, sm_fuse_test},
	// 收到EV_1S，更新状态
  {SM_FUSE_TEST<<4|SM_FUSE_TEST_FUSE0_BROKE, EV_1S, SM_FUSE_TEST<<4|SM_FUSE_TEST_FUSE0_BROKE, sm_fuse_test},
  // mod0 切换到测试 fuse1 short
  {SM_FUSE_TEST<<4|SM_FUSE_TEST_FUSE0_BROKE, EV_KEY_MOD_PRESS, SM_FUSE_TEST<<4|SM_FUSE_TEST_FUSE1_SHORT, sm_fuse_test},
  // mod1 切换回时钟模式
  {SM_FUSE_TEST<<4|SM_FUSE_TEST_FUSE0_BROKE, EV_KEY_MOD_LPRESS, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_INIT, sm_clock_display},
  // set1 切换到参数设置
  {SM_FUSE_TEST<<4|SM_FUSE_TEST_FUSE0_BROKE, EV_KEY_SET_LPRESS, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_INIT, sm_fuse_param},
  
  // set0启动测试
  {SM_FUSE_TEST<<4|SM_FUSE_TEST_FUSE1_SHORT, EV_KEY_SET_PRESS, SM_FUSE_TEST<<4|SM_FUSE_TEST_FUSE1_SHORT, sm_fuse_test},
  // 测试fuse1 short 收到EV_FUSE1_SHORT, 更新显示
  {SM_FUSE_TEST<<4|SM_FUSE_TEST_FUSE1_SHORT, EV_FUSE1_SHORT, SM_FUSE_TEST<<4|SM_FUSE_TEST_FUSE1_SHORT, sm_fuse_test},
	// 收到EV_1S，更新状态
  {SM_FUSE_TEST<<4|SM_FUSE_TEST_FUSE1_SHORT, EV_1S, SM_FUSE_TEST<<4|SM_FUSE_TEST_FUSE1_SHORT, sm_fuse_test},
  // mod0 切换到测试 fuse1 broke
  {SM_FUSE_TEST<<4|SM_FUSE_TEST_FUSE1_SHORT, EV_KEY_MOD_PRESS, SM_FUSE_TEST<<4|SM_FUSE_TEST_FUSE1_BROKE, sm_fuse_test},
  // mod1 切换回时钟模式
  {SM_FUSE_TEST<<4|SM_FUSE_TEST_FUSE1_SHORT, EV_KEY_MOD_LPRESS, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_INIT, sm_clock_display},
  // set1 切换到参数设置
  {SM_FUSE_TEST<<4|SM_FUSE_TEST_FUSE1_SHORT, EV_KEY_SET_LPRESS, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_INIT, sm_fuse_param},

  
  // set0启动测试
  {SM_FUSE_TEST<<4|SM_FUSE_TEST_FUSE1_BROKE, EV_KEY_SET_PRESS, SM_FUSE_TEST<<4|SM_FUSE_TEST_FUSE1_BROKE, sm_fuse_test},
  // 测试fuse1 broke 收到EV_FUSE1_BROKE, 更新显示
  {SM_FUSE_TEST<<4|SM_FUSE_TEST_FUSE1_BROKE, EV_FUSE1_BROKE, SM_FUSE_TEST<<4|SM_FUSE_TEST_FUSE1_BROKE, sm_fuse_test},
	// 收到EV_1S，更新状态
  {SM_FUSE_TEST<<4|SM_FUSE_TEST_FUSE1_BROKE, EV_1S, SM_FUSE_TEST<<4|SM_FUSE_TEST_FUSE1_BROKE, sm_fuse_test},
  // mod0 切换到测试tripwire
  {SM_FUSE_TEST<<4|SM_FUSE_TEST_FUSE1_BROKE, EV_KEY_MOD_PRESS, SM_FUSE_TEST<<4|SM_FUSE_TEST_TRIPWIRE, sm_fuse_test},
  // mod1 切换回时钟模式
  {SM_FUSE_TEST<<4|SM_FUSE_TEST_FUSE1_BROKE, EV_KEY_MOD_LPRESS, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_INIT, sm_clock_display},
  // set1 切换到参数设置
  {SM_FUSE_TEST<<4|SM_FUSE_TEST_FUSE1_BROKE, EV_KEY_SET_LPRESS, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_INIT, sm_fuse_param},
  
  // set0启动测试
  {SM_FUSE_TEST<<4|SM_FUSE_TEST_TRIPWIRE, EV_KEY_SET_PRESS, SM_FUSE_TEST<<4|SM_FUSE_TEST_TRIPWIRE, sm_fuse_test},
  // 收到 EV_TRIPWIRE 更新显示
  {SM_FUSE_TEST<<4|SM_FUSE_TEST_TRIPWIRE, EV_TRIPWIRE, SM_FUSE_TEST<<4|SM_FUSE_TEST_TRIPWIRE, sm_fuse_test},
	// 收到EV_1S，更新状态
  {SM_FUSE_TEST<<4|SM_FUSE_TEST_TRIPWIRE, EV_1S, SM_FUSE_TEST<<4|SM_FUSE_TEST_TRIPWIRE, sm_fuse_test},
  // mod0 切换到测试thermo hi
  {SM_FUSE_TEST<<4|SM_FUSE_TEST_TRIPWIRE, EV_KEY_MOD_PRESS, SM_FUSE_TEST<<4|SM_FUSE_TEST_THERMO_HI, sm_fuse_test},
  // mod1 切换回时钟模式
  {SM_FUSE_TEST<<4|SM_FUSE_TEST_TRIPWIRE, EV_KEY_MOD_LPRESS, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_INIT, sm_clock_display},
  // set1 切换到参数设置
  {SM_FUSE_TEST<<4|SM_FUSE_TEST_TRIPWIRE, EV_KEY_SET_LPRESS, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_INIT, sm_fuse_param},
  
  // set0启动测试
  {SM_FUSE_TEST<<4|SM_FUSE_TEST_THERMO_HI, EV_KEY_SET_PRESS, SM_FUSE_TEST<<4|SM_FUSE_TEST_THERMO_HI, sm_fuse_test},
  // 收到EV_THERMO_HI，更新显示
  {SM_FUSE_TEST<<4|SM_FUSE_TEST_THERMO_HI, EV_THERMO_HI, SM_FUSE_TEST<<4|SM_FUSE_TEST_THERMO_HI, sm_fuse_test},
	// 收到EV_1S，更新状态
  {SM_FUSE_TEST<<4|SM_FUSE_TEST_THERMO_HI, EV_1S, SM_FUSE_TEST<<4|SM_FUSE_TEST_THERMO_HI, sm_fuse_test},
  // mod0 切换到测试thermo lo
  {SM_FUSE_TEST<<4|SM_FUSE_TEST_THERMO_HI, EV_KEY_MOD_PRESS, SM_FUSE_TEST<<4|SM_FUSE_TEST_THERMO_LO, sm_fuse_test},
  // mod1 切换回时钟模式
  {SM_FUSE_TEST<<4|SM_FUSE_TEST_THERMO_HI, EV_KEY_MOD_LPRESS, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_INIT, sm_clock_display},
  // set1 切换到参数设置
  {SM_FUSE_TEST<<4|SM_FUSE_TEST_THERMO_HI, EV_KEY_SET_LPRESS, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_INIT, sm_fuse_param},
  
  // set0启动测试
  {SM_FUSE_TEST<<4|SM_FUSE_TEST_THERMO_LO, EV_KEY_SET_PRESS, SM_FUSE_TEST<<4|SM_FUSE_TEST_THERMO_LO, sm_fuse_test},
  // 收到EV_THERMO_LO，更新显示
  {SM_FUSE_TEST<<4|SM_FUSE_TEST_THERMO_LO, EV_THERMO_LO, SM_FUSE_TEST<<4|SM_FUSE_TEST_THERMO_LO, sm_fuse_test},
	// 收到EV_1S，更新状态
  {SM_FUSE_TEST<<4|SM_FUSE_TEST_THERMO_LO, EV_1S, SM_FUSE_TEST<<4|SM_FUSE_TEST_THERMO_LO, sm_fuse_test},
  // mod0 切换到测试 hg
  {SM_FUSE_TEST<<4|SM_FUSE_TEST_THERMO_LO, EV_KEY_MOD_PRESS, SM_FUSE_TEST<<4|SM_FUSE_TEST_HG, sm_fuse_test},
  // mod1 切换回时钟模式
  {SM_FUSE_TEST<<4|SM_FUSE_TEST_THERMO_LO, EV_KEY_MOD_LPRESS, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_INIT, sm_clock_display},
  // set1 切换到参数设置
  {SM_FUSE_TEST<<4|SM_FUSE_TEST_THERMO_LO, EV_KEY_SET_LPRESS, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_INIT, sm_fuse_param},
  
  // set0启动测试
  {SM_FUSE_TEST<<4|SM_FUSE_TEST_HG, EV_KEY_SET_PRESS, SM_FUSE_TEST<<4|SM_FUSE_TEST_HG, sm_fuse_test},
  // 收到EV_ROTATE，更新显示
  {SM_FUSE_TEST<<4|SM_FUSE_TEST_HG, EV_ROTATE_HG, SM_FUSE_TEST<<4|SM_FUSE_TEST_HG, sm_fuse_test},
	// 收到EV_1S，更新状态
	{SM_FUSE_TEST<<4|SM_FUSE_TEST_HG, EV_1S, SM_FUSE_TEST<<4|SM_FUSE_TEST_HG, sm_fuse_test},
  // mod0 切换到测试 gyro
  {SM_FUSE_TEST<<4|SM_FUSE_TEST_HG, EV_KEY_MOD_PRESS, SM_FUSE_TEST<<4|SM_FUSE_TEST_GYRO, sm_fuse_test},
  // mod1 切换回时钟模式
  {SM_FUSE_TEST<<4|SM_FUSE_TEST_HG, EV_KEY_MOD_LPRESS, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_INIT, sm_clock_display},
  // set1 切换到参数设置
  {SM_FUSE_TEST<<4|SM_FUSE_TEST_HG, EV_KEY_SET_LPRESS, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_INIT, sm_fuse_mode},

  
  // set0启动测试
  {SM_FUSE_TEST<<4|SM_FUSE_TEST_GYRO, EV_KEY_SET_PRESS, SM_FUSE_TEST<<4|SM_FUSE_TEST_GYRO, sm_fuse_test},
  // 收到EV_ROTATE，更新显示
  {SM_FUSE_TEST<<4|SM_FUSE_TEST_GYRO, EV_ROTATE_GYRO, SM_FUSE_TEST<<4|SM_FUSE_TEST_GYRO, sm_fuse_test},
  // 收到EV_ACC，更新显示
  {SM_FUSE_TEST<<4|SM_FUSE_TEST_GYRO, EV_ACC_GYRO, SM_FUSE_TEST<<4|SM_FUSE_TEST_GYRO, sm_fuse_test},
  // 收到EV_DROP，更新显示
  {SM_FUSE_TEST<<4|SM_FUSE_TEST_GYRO, EV_DROP_GYRO, SM_FUSE_TEST<<4|SM_FUSE_TEST_GYRO, sm_fuse_test},  
	// 收到EV_1S，更新状态
  {SM_FUSE_TEST<<4|SM_FUSE_TEST_GYRO, EV_1S, SM_FUSE_TEST<<4|SM_FUSE_TEST_GYRO, sm_fuse_test},
  // mod0 切换到测试 fuse0 short
  {SM_FUSE_TEST<<4|SM_FUSE_TEST_GYRO, EV_KEY_MOD_PRESS, SM_FUSE_TEST<<4|SM_FUSE_TEST_FUSE0_SHORT, sm_fuse_test},
   // mod1 切换回时钟模式
  {SM_FUSE_TEST<<4|SM_FUSE_TEST_GYRO, EV_KEY_MOD_SET_LPRESS, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_INIT, sm_clock_display},
  // set1 切换到参数设置
  {SM_FUSE_TEST<<4|SM_FUSE_TEST_GYRO, EV_KEY_SET_LPRESS, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_INIT, sm_fuse_param},
};

static const struct sm_trans code sm_trans_fuse_mode[] = {  
  /* SM_FUSE_MODE */
  // 从别的状态切过来，防止误操作
  {SM_FUSE_MODE<<4|SM_FUSE_MODE_INIT, EV_KEY_MOD_UP, SM_FUSE_MODE<<4|SM_FUSE_MODE_TIMER, sm_fuse_mode},
  // set0 模式选择
  {SM_FUSE_MODE<<4|SM_FUSE_MODE_TIMER, EV_KEY_SET_PRESS, SM_FUSE_MODE<<4|SM_FUSE_MODE_TIMER, sm_fuse_mode},
  // mod0 切换到触碰模式
  {SM_FUSE_MODE<<4|SM_FUSE_MODE_TIMER, EV_KEY_MOD_PRESS, SM_FUSE_MODE<<4|SM_FUSE_MODE_GRENADE, sm_fuse_mode},
  // EV_FUSE_SEL  进入armed
  {SM_FUSE_MODE<<4|SM_FUSE_MODE_TIMER, EV_FUSE_SEL0, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_INIT, sm_fuse_timer},
  // set0 模式选择
  {SM_FUSE_MODE<<4|SM_FUSE_MODE_GRENADE, EV_KEY_SET_PRESS, SM_FUSE_MODE<<4|SM_FUSE_MODE_GRENADE, sm_fuse_mode},
  // mod0 切换到定时模式
  {SM_FUSE_MODE<<4|SM_FUSE_MODE_GRENADE, EV_KEY_MOD_PRESS, SM_FUSE_MODE<<4|SM_FUSE_MODE_TIMER, sm_fuse_mode},
  // EV_FUSE_SEL  进入armed
  {SM_FUSE_MODE<<4|SM_FUSE_MODE_GRENADE, EV_FUSE_SEL0, SM_FUSE_GRENADE<<4|SM_FUSE_GRENADE_INIT, sm_fuse_grenade},
};

static const struct sm_trans code sm_trans_fuse_param[] = { 
  /* SM_FUSE_PARAM */
  {SM_FUSE_PARAM<<4|SM_FUSE_PARAM_INIT, EV_KEY_MOD_UP, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_YY, sm_fuse_param},
  // set0 调整年
  {SM_FUSE_PARAM<<4|SM_FUSE_PARAM_YY, EV_KEY_SET_PRESS, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_YY, sm_fuse_param},
  {SM_FUSE_PARAM<<4|SM_FUSE_PARAM_YY, EV_KEY_SET_LPRESS, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_YY, sm_fuse_param},
  {SM_FUSE_PARAM<<4|SM_FUSE_PARAM_YY, EV_KEY_SET_UP, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_YY, sm_fuse_param},  
  // mod0 切换到调整月
  {SM_FUSE_PARAM<<4|SM_FUSE_PARAM_YY, EV_KEY_MOD_PRESS, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_MO, sm_fuse_param},
  // set0/1 调整月
  {SM_FUSE_PARAM<<4|SM_FUSE_PARAM_MO, EV_KEY_SET_PRESS, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_MO, sm_fuse_param},
  {SM_FUSE_PARAM<<4|SM_FUSE_PARAM_MO, EV_KEY_SET_LPRESS, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_MO, sm_fuse_param},
  {SM_FUSE_PARAM<<4|SM_FUSE_PARAM_MO, EV_KEY_SET_UP, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_MO, sm_fuse_param},
  // mod0 切换到调整日
  {SM_FUSE_PARAM<<4|SM_FUSE_PARAM_MM, EV_KEY_MOD_PRESS, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_DD, sm_fuse_param},
  // set0/1 调整日
  {SM_FUSE_PARAM<<4|SM_FUSE_PARAM_DD, EV_KEY_SET_PRESS, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_DD, sm_fuse_param},
  {SM_FUSE_PARAM<<4|SM_FUSE_PARAM_DD, EV_KEY_SET_LPRESS, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_DD, sm_fuse_param},
  {SM_FUSE_PARAM<<4|SM_FUSE_PARAM_DD, EV_KEY_SET_UP, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_DD, sm_fuse_param},
  // mod0 切换调整时
  {SM_FUSE_PARAM<<4|SM_FUSE_PARAM_DD, EV_KEY_MOD_PRESS, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_HH, sm_fuse_param},
  // set0/1 调整时
  {SM_FUSE_PARAM<<4|SM_FUSE_PARAM_HH, EV_KEY_SET_PRESS, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_HH, sm_fuse_param},
  {SM_FUSE_PARAM<<4|SM_FUSE_PARAM_HH, EV_KEY_SET_LPRESS, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_HH, sm_fuse_param},
  {SM_FUSE_PARAM<<4|SM_FUSE_PARAM_HH, EV_KEY_SET_UP, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_HH, sm_fuse_param},
  // mod0 切换调整分
  {SM_FUSE_PARAM<<4|SM_FUSE_PARAM_HH, EV_KEY_MOD_PRESS, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_MM, sm_fuse_param},
  // set0/1 调整分
  {SM_FUSE_PARAM<<4|SM_FUSE_PARAM_MM, EV_KEY_SET_PRESS, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_MM, sm_fuse_param},
  {SM_FUSE_PARAM<<4|SM_FUSE_PARAM_MM, EV_KEY_SET_LPRESS, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_MM, sm_fuse_param},
  {SM_FUSE_PARAM<<4|SM_FUSE_PARAM_MM, EV_KEY_SET_UP, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_MM, sm_fuse_param},
  // mod0 切换调整秒
  {SM_FUSE_PARAM<<4|SM_FUSE_PARAM_MM, EV_KEY_MOD_PRESS, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_SS, sm_fuse_param},
  // set0/1 调整秒
  {SM_FUSE_PARAM<<4|SM_FUSE_PARAM_SS, EV_KEY_SET_PRESS, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_SS, sm_fuse_param},
  {SM_FUSE_PARAM<<4|SM_FUSE_PARAM_SS, EV_KEY_SET_LPRESS, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_SS, sm_fuse_param},
  {SM_FUSE_PARAM<<4|SM_FUSE_PARAM_SS, EV_KEY_SET_UP, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_SS, sm_fuse_param},
  // mod0 切换HG on/off
  {SM_FUSE_PARAM<<4|SM_FUSE_PARAM_SS, EV_KEY_MOD_PRESS, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_HG_ONOFF, sm_fuse_param},
  // set0 调整HG on/off
  {SM_FUSE_PARAM<<4|SM_FUSE_PARAM_HG_ONOFF, EV_KEY_SET_PRESS, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_HG_ONOFF, sm_fuse_param},
  // mod0 切换GYRO on/off
  {SM_FUSE_PARAM<<4|SM_FUSE_PARAM_HG_ONOFF, EV_KEY_MOD_PRESS, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_GYRO_ONOFF, sm_fuse_param},
  // set0 调整GYRO on/off
  {SM_FUSE_PARAM<<4|SM_FUSE_PARAM_GYRO_ONOFF, EV_KEY_SET_PRESS, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_GYRO_ONOFF, sm_fuse_param},  
  // mod0 切换THERMO_HI on/off
  {SM_FUSE_PARAM<<4|SM_FUSE_PARAM_GYRO_ONOFF, EV_KEY_MOD_PRESS, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_THERMO_HI_ONOFF, sm_fuse_param},
  // set0 调整THERMO_HI on/off
  {SM_FUSE_PARAM<<4|SM_FUSE_PARAM_THERMO_HI_ONOFF, EV_KEY_SET_PRESS, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_THERMO_HI_ONOFF, sm_fuse_param},
  // mod0 切换THERMO_LO on/off
  {SM_FUSE_PARAM<<4|SM_FUSE_PARAM_THERMO_HI_ONOFF, EV_KEY_MOD_PRESS, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_THERMO_LO_ONOFF, sm_fuse_param},
  // set0 调整THERMO_LO on/off
  {SM_FUSE_PARAM<<4|SM_FUSE_PARAM_THERMO_LO_ONOFF, EV_KEY_SET_PRESS, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_THERMO_LO_ONOFF, sm_fuse_param},
  // mod0 切换TRIPWIRE on/off
  {SM_FUSE_PARAM<<4|SM_FUSE_PARAM_THERMO_LO_ONOFF, EV_KEY_MOD_PRESS, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_TRIPWIRE_ONOFF, sm_fuse_param},
  // set0 调整TRIPWIRE on/off
  {SM_FUSE_PARAM<<4|SM_FUSE_PARAM_TRIPWIRE_ONOFF, EV_KEY_SET_PRESS, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_TRIPWIRE_ONOFF, sm_fuse_param},
  // mod0 切换password 
  {SM_FUSE_PARAM<<4|SM_FUSE_PARAM_TRIPWIRE_ONOFF, EV_KEY_MOD_PRESS, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_PASSWORD, sm_fuse_param},
  // set0 调整password 
  {SM_FUSE_PARAM<<4|SM_FUSE_PARAM_PASSWORD, EV_KEY_SET_PRESS, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_PASSWORD, sm_fuse_param},
  // mod0 下一数字
  {SM_FUSE_PARAM<<4|SM_FUSE_PARAM_PASSWORD, EV_KEY_MOD_PRESS, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_PASSWORD, sm_fuse_param}, 
  // 结尾从头开始
  {SM_FUSE_PARAM<<4|SM_FUSE_PARAM_PASSWORD, EV_FUSE_SEL0, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_YY, sm_fuse_param},  
  // mod1 跳转电路测试
  {SM_FUSE_PARAM<<4|SM_FUSE_PARAM_PASSWORD, EV_KEY_MOD_LPRESS, SM_FUSE_TEST<<4|SM_FUSE_TEST_INIT, sm_fuse_test}, 
};

static const struct sm_trans code sm_trans_fuse_timer[] = { 
  /* SM_FUSE_TIMER */ 
  // 过1秒进入armed状态
  {SM_FUSE_TIMER<<4|SM_FUSE_TIMER_INIT, EV_1S, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_ARMED, sm_fuse_timer},
  // 更新倒计时
  {SM_FUSE_TIMER<<4|SM_FUSE_TIMER_ARMED, EV_250MS, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_ARMED, sm_fuse_timer},
  // mod0 进入密码验证
  {SM_FUSE_TIMER<<4|SM_FUSE_TIMER_ARMED, EV_KEY_MOD_PRESS, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_VERIFY, sm_fuse_timer}, 
  // mod0 下一数字
  {SM_FUSE_TIMER<<4|SM_FUSE_TIMER_VERIFY, EV_KEY_MOD_PRESS, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_VERIFY, sm_fuse_timer}, 
  // 验证OK,解除，进入电路测试
  {SM_FUSE_TIMER<<4|SM_FUSE_TIMER_VERIFY, EV_FUSE_SEL0, SM_FUSE_TEST<<4|SM_FUSE_TEST_INIT, sm_fuse_param},
  // 三次验证失败,触发
  {SM_FUSE_TIMER<<4|SM_FUSE_TIMER_VERIFY, EV_FUSE_SEL1, SM_FUSE_DETONATE<<4|SM_FUSE_DETONATE_INIT, sm_fuse_detonate},
  // 计时器时间到,触发
  {SM_FUSE_TIMER<<4|SM_FUSE_TIMER_ARMED, EV_COUNTER, SM_FUSE_DETONATE<<4|SM_FUSE_DETONATE_INIT, sm_fuse_detonate},
  // fuse0短路,触发
  {SM_FUSE_TIMER<<4|SM_FUSE_TIMER_ARMED, EV_FUSE0_SHORT, SM_FUSE_DETONATE<<4|SM_FUSE_DETONATE_INIT, sm_fuse_detonate},
  // fuse0剪断,触发
  {SM_FUSE_TIMER<<4|SM_FUSE_TIMER_ARMED, EV_FUSE0_BROKE, SM_FUSE_DETONATE<<4|SM_FUSE_DETONATE_INIT, sm_fuse_detonate},
  // fuse1短路,触发
  {SM_FUSE_TIMER<<4|SM_FUSE_TIMER_ARMED, EV_FUSE1_SHORT, SM_FUSE_DETONATE<<4|SM_FUSE_DETONATE_INIT, sm_fuse_detonate},
  // fuse1剪断,触发
  {SM_FUSE_TIMER<<4|SM_FUSE_TIMER_ARMED, EV_FUSE1_BROKE, SM_FUSE_DETONATE<<4|SM_FUSE_DETONATE_INIT, sm_fuse_detonate},
  // 姿态变化,触发
  {SM_FUSE_TIMER<<4|SM_FUSE_TIMER_ARMED, EV_ROTATE_GYRO, SM_FUSE_DETONATE<<4|SM_FUSE_DETONATE_INIT, sm_fuse_detonate},
  // 姿态变化,触发
  {SM_FUSE_TIMER<<4|SM_FUSE_TIMER_ARMED, EV_ROTATE_HG, SM_FUSE_DETONATE<<4|SM_FUSE_DETONATE_INIT, sm_fuse_detonate},
  // 加速度变化,触发
  {SM_FUSE_TIMER<<4|SM_FUSE_TIMER_ARMED, EV_ACC_GYRO, SM_FUSE_DETONATE<<4|SM_FUSE_DETONATE_INIT, sm_fuse_detonate},
  // 温度太高,触发
  {SM_FUSE_TIMER<<4|SM_FUSE_TIMER_ARMED, EV_THERMO_HI, SM_FUSE_DETONATE<<4|SM_FUSE_DETONATE_INIT, sm_fuse_detonate},
  // 温度太低,触发
  {SM_FUSE_TIMER<<4|SM_FUSE_TIMER_ARMED, EV_THERMO_LO, SM_FUSE_DETONATE<<4|SM_FUSE_DETONATE_INIT, sm_fuse_detonate},
  // tripwire剪断,触发
  {SM_FUSE_TIMER<<4|SM_FUSE_TIMER_ARMED, EV_TRIPWIRE, SM_FUSE_DETONATE<<4|SM_FUSE_DETONATE_INIT, sm_fuse_detonate},
  // 超时，进入节电
  {SM_FUSE_TIMER<<4|SM_FUSE_TIMER_VERIFY, EV_POWER_SAVE, SM_FUSE_POWERSAVE<<4|SM_FUSE_POWERSAVE_INIT, sm_fuse_powersave},
};

static const struct sm_trans code sm_trans_fuse_grenade[] = { 
  /* SM_FUSE_GRENADE */
  // 过1秒进入pre-armed状态
  {SM_FUSE_GRENADE<<4|SM_FUSE_GRENADE_INIT, EV_1S, SM_FUSE_GRENADE<<4|SM_FUSE_GRENADE_PRE_ARMED, sm_fuse_grenade},
  // 收到mod1，解除
  {SM_FUSE_GRENADE<<4|SM_FUSE_GRENADE_PRE_ARMED, EV_KEY_MOD_LPRESS, SM_FUSE_TEST<<4|SM_FUSE_TEST_INIT, sm_fuse_test},
  // 收到EV_ACC,测试加速度改变
  {SM_FUSE_GRENADE<<4|SM_FUSE_GRENADE_PRE_ARMED, EV_ACC_GYRO, SM_FUSE_GRENADE<<4|SM_FUSE_GRENADE_PRE_ARMED, sm_fuse_grenade},
  // 如果是脱手（失重），进入ARMED
  {SM_FUSE_GRENADE<<4|SM_FUSE_GRENADE_PRE_ARMED, EV_FUSE_SEL0, SM_FUSE_GRENADE<<4|SM_FUSE_GRENADE_ARMED, sm_fuse_grenade},
  // 收到EV_ACC,测试加速度改变
  {SM_FUSE_GRENADE<<4|SM_FUSE_GRENADE_ARMED, EV_ACC_GYRO, SM_FUSE_GRENADE<<4|SM_FUSE_GRENADE_ARMED, sm_fuse_grenade},
  // 落地/触碰,触发
  {SM_FUSE_PARAM<<4|SM_FUSE_GRENADE_ARMED, EV_FUSE_SEL0, SM_FUSE_DETONATE<<4|SM_FUSE_DETONATE_INIT, sm_fuse_detonate},
};

static const struct sm_trans code sm_trans_fuse_detonate[] = { 
  /* SM_FUSE_DETONATE */
  // 过250ms进入charge状态
  {SM_FUSE_DETONATE<<4|SM_FUSE_DETONATE_INIT, EV_250MS, SM_FUSE_DETONATE<<4|SM_FUSE_DETONATE_CHARGE, sm_fuse_detonate},
  // 持续charge 30秒
  {SM_FUSE_DETONATE<<4|SM_FUSE_DETONATE_CHARGE, EV_1S, SM_FUSE_DETONATE<<4|SM_FUSE_DETONATE_CHARGE, sm_fuse_detonate},
  // 通电状态，mod1进入电路测试
  {SM_FUSE_DETONATE<<4|SM_FUSE_DETONATE_CHARGE, EV_KEY_MOD_LPRESS, SM_FUSE_TEST<<4|SM_FUSE_TEST_INIT, sm_fuse_test},
};

static const struct sm_trans code sm_trans_fuse_powersave[] = { 
  /* SM_FUSE_POWERSAVE */
  // 过250ms进入powersave
  {SM_FUSE_POWERSAVE<<4|SM_FUSE_POWERSAVE_INIT, EV_250MS, SM_FUSE_POWERSAVE<<4|SM_FUSE_POWERSAVE_PS, sm_fuse_powersave},
  // set0 回到 SM_FUSE_TIMER
  {SM_FUSE_POWERSAVE<<4|SM_FUSE_POWERSAVE_PS, EV_KEY_SET_PRESS, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_ARMED, sm_fuse_timer},
  // mod0 回到 SM_FUSE_TIMER
  {SM_FUSE_POWERSAVE<<4|SM_FUSE_POWERSAVE_PS, EV_KEY_MOD_PRESS, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_ARMED, sm_fuse_timer},  
  // 计时器时间到,触发
  {SM_FUSE_POWERSAVE<<4|SM_FUSE_POWERSAVE_PS, EV_COUNTER, SM_FUSE_DETONATE<<4|SM_FUSE_DETONATE_INIT, sm_fuse_detonate},
  // fuse0短路,触发
  {SM_FUSE_POWERSAVE<<4|SM_FUSE_POWERSAVE_PS, EV_FUSE0_SHORT, SM_FUSE_DETONATE<<4|SM_FUSE_DETONATE_INIT, sm_fuse_detonate},
  // fuse0剪断,触发
  {SM_FUSE_POWERSAVE<<4|SM_FUSE_POWERSAVE_PS, EV_FUSE0_BROKE, SM_FUSE_DETONATE<<4|SM_FUSE_DETONATE_INIT, sm_fuse_detonate},
  // fuse1短路,触发
  {SM_FUSE_POWERSAVE<<4|SM_FUSE_POWERSAVE_PS, EV_FUSE1_SHORT, SM_FUSE_DETONATE<<4|SM_FUSE_DETONATE_INIT, sm_fuse_detonate},
  // fuse1剪断,触发
  {SM_FUSE_POWERSAVE<<4|SM_FUSE_POWERSAVE_PS, EV_FUSE1_BROKE, SM_FUSE_DETONATE<<4|SM_FUSE_DETONATE_INIT, sm_fuse_detonate},
  // 姿态变化,触发
  {SM_FUSE_POWERSAVE<<4|SM_FUSE_POWERSAVE_PS, EV_ROTATE_GYRO, SM_FUSE_DETONATE<<4|SM_FUSE_DETONATE_INIT, sm_fuse_detonate},
  // 姿态变化,触发
  {SM_FUSE_POWERSAVE<<4|SM_FUSE_POWERSAVE_PS, EV_ROTATE_HG, SM_FUSE_DETONATE<<4|SM_FUSE_DETONATE_INIT, sm_fuse_detonate},
  // 加速度变化,触发
  {SM_FUSE_POWERSAVE<<4|SM_FUSE_POWERSAVE_PS, EV_ACC_GYRO, SM_FUSE_DETONATE<<4|SM_FUSE_DETONATE_INIT, sm_fuse_detonate},
  // 温度太高,触发
  {SM_FUSE_POWERSAVE<<4|SM_FUSE_POWERSAVE_PS, EV_THERMO_HI, SM_FUSE_DETONATE<<4|SM_FUSE_DETONATE_INIT, sm_fuse_detonate},
  // 温度太低,触发
  {SM_FUSE_POWERSAVE<<4|SM_FUSE_POWERSAVE_PS, EV_THERMO_LO, SM_FUSE_DETONATE<<4|SM_FUSE_DETONATE_INIT, sm_fuse_detonate},
  // tripwire剪断,触发
  {SM_FUSE_POWERSAVE<<4|SM_FUSE_POWERSAVE_PS, EV_TRIPWIRE, SM_FUSE_DETONATE<<4|SM_FUSE_DETONATE_INIT, sm_fuse_detonate},
};  

struct sm_trans_table
{
  struct sm_trans * table;
  unsigned char cnt;
};

static const struct sm_trans_table code sm[] = {
  {sm_trans_clock_display, sizeof(sm_trans_clock_display)/ sizeof(struct sm_trans)},
  {sm_trans_clock_mod_time,sizeof(sm_trans_clock_mod_time)/ sizeof(struct sm_trans)},
  {sm_trans_clock_mod_alarm,sizeof(sm_trans_clock_mod_alarm)/ sizeof(struct sm_trans)},
  {sm_trans_clock_mod_global_flag,sizeof(sm_trans_clock_mod_global_flag)/ sizeof(struct sm_trans)},
  {sm_trans_clock_powersave,sizeof(sm_trans_clock_powersave)/ sizeof(struct sm_trans)},
  {sm_trans_clock_alarm,sizeof(sm_trans_clock_alarm)/ sizeof(struct sm_trans)},
  {sm_trans_clock_timer,sizeof(sm_trans_clock_timer)/ sizeof(struct sm_trans)},
  {sm_trans_clock_counter,sizeof(sm_trans_clock_counter)/ sizeof(struct sm_trans)},
  {sm_trans_fuse_test,sizeof(sm_trans_fuse_test)/ sizeof(struct sm_trans)},
  {sm_trans_fuse_mode,sizeof(sm_trans_fuse_mode)/ sizeof(struct sm_trans)},
  {sm_trans_fuse_param,sizeof(sm_trans_fuse_param)/ sizeof(struct sm_trans)},
  {sm_trans_fuse_timer,sizeof(sm_trans_fuse_timer)/ sizeof(struct sm_trans)},
  {sm_trans_fuse_grenade,sizeof(sm_trans_fuse_grenade)/ sizeof(struct sm_trans)},
  {sm_trans_fuse_detonate,sizeof(sm_trans_fuse_detonate)/ sizeof(struct sm_trans)},
  {sm_trans_fuse_powersave,sizeof(sm_trans_fuse_powersave)/ sizeof(struct sm_trans)},
};

static unsigned char sm_state; // hi 4 bits : state, lo 4 bits: sub-state 

/* 不做任何过滤 */
void null_proc(enum task_events ev)
{
  run_state_machine(ev);
}

void run_state_machine(enum task_events ev)
{
  unsigned char c;
  unsigned char newstate;
  unsigned char index;
  
  index = get_sm_state(sm_state);
  
  for (c = 0 ; c < sm[index].cnt ; c++) {
    if(sm_state == sm[index].table[c].from_state && ev == sm[index].table[c].event) {
      newstate = sm[index].table[c].to_state;
      CDBG("SM: [table %bu][slot %bu] ev = %bd %bd|%bd -> %bd|%bd\n", index, c, ev,
        get_sm_state(sm_state), get_sm_ss_state(sm_state), 
        get_sm_state(sm[index].table[c].to_state), get_sm_ss_state(sm[index].table[c].to_state));
      sm[index].table[c].sm_proc(sm_state, sm[index].table[c].to_state, ev);
      sm_state = sm[index].table[c].to_state;
      break;
    }
  }
}


void sm_initialize (void) 
{
  CDBG("sm_initialize\n");
  sm_state = SM_CLOCK_DISPLAY|SM_CLOCK_DISPLAY_INIT;
  
  alarm_switch_on();
  lt_timer_switch_off();
  
  set_task(EV_KEY_MOD_UP);
}
