#include <stdio.h>
#include <string.h>
#include "sm.h"
#include "debug.h"
#include "led.h"
#include "beeper.h"
#include "alarm.h"
#include "lt_timer.h"
#include "rtc.h"
#include "delay_task.h"

/* state machine */
#include "sm_clock_display.h"
#include "sm_clock_mod_time.h"
#include "sm_clock_mod_alarm.h"
#include "sm_clock_powersave.h"
#include "sm_clock_counter.h"
#include "sm_clock_timer.h"
#include "sm_clock_alarm.h"

#include "sm_power_pack_display.h"
#include "sm_power_pack_powersave.h"

#include "sm_fuse_test.h"
#include "sm_fuse_param.h"
#include "sm_fuse_timer.h"
#include "sm_fuse_detonate.h"
#include "sm_fuse_powersave.h"

#include "sm_global_flag_mod.h"

// state machine translate defines
// 超级复杂变态
// 
static const struct sm_trans code sm_trans_clock_display[] = 
{
  /* SM_CLOCK_DISPLAY */
  // 从别的状态切过来，防止误操作
  {SM_CLOCK, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_INIT, EV_KEY_MOD_UP, SM_CLOCK, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_HHMMSS, sm_clock_display_submod0},  
  // 按mod0显示年月日
  {SM_CLOCK, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_HHMMSS, EV_KEY_MOD_PRESS, SM_CLOCK, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_YYMMDD, sm_clock_display_submod1},
  // 按mod1进入修改时间模式
  {SM_CLOCK, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_HHMMSS, EV_KEY_MOD_LPRESS, SM_CLOCK, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_INIT, sm_clock_mod_time_init},
  // 闹钟0响了
  {SM_CLOCK, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_HHMMSS, EV_ALARM0, SM_CLOCK, SM_CLOCK_ALARM<<4|SM_CLOCK_ALARM_HIT_ALARM0, sm_clock_alarm},
  // 闹钟1响了
  {SM_CLOCK, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_HHMMSS, EV_ALARM1, SM_CLOCK, SM_CLOCK_ALARM<<4|SM_CLOCK_ALARM_HIT_ALARM1, sm_clock_alarm},
  // 该进入节电模式了
  {SM_CLOCK, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_HHMMSS, EV_POWER_SAVE, SM_CLOCK, SM_CLOCK_POWERSAVE<<4|SM_CLOCK_POWERSAVE_INIT, sm_clock_powersave},
  // 进入跑表功能
  {SM_CLOCK, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_HHMMSS, EV_KEY_SET_LPRESS, SM_CLOCK, SM_CLOCK_TIMER<<4|SM_CLOCK_TIMER_INIT, sm_clock_timer_init},
  // 1S探测下睡眠超时时间
  {SM_CLOCK, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_HHMMSS, EV_1S, SM_CLOCK, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_HHMMSS, sm_clock_display_submod0},
  
  // 按modset1进入power_pack功能集合
  {SM_CLOCK, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_HHMMSS, EV_KEY_MOD_SET_LPRESS, SM_POWER_PACK, SM_POWER_PACK_DISPLAY<<4|SM_POWER_PACK_DISPLAY_INIT, sm_power_pack_display_init},

  // 按mod0显示星期几
  {SM_CLOCK, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_YYMMDD, EV_KEY_MOD_PRESS, SM_CLOCK, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_WEEK, sm_clock_display_submod2},
  // set0回到时分秒显示模式
  {SM_CLOCK, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_YYMMDD, EV_KEY_SET_PRESS, SM_CLOCK, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_HHMMSS, sm_clock_display_submod0},
  // 闹钟0响了
  {SM_CLOCK, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_YYMMDD, EV_ALARM0, SM_CLOCK, SM_CLOCK_ALARM<<4|SM_CLOCK_ALARM_HIT_ALARM0, sm_clock_alarm},
  // 闹钟1响了
  {SM_CLOCK, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_YYMMDD, EV_ALARM1, SM_CLOCK, SM_CLOCK_ALARM<<4|SM_CLOCK_ALARM_HIT_ALARM1, sm_clock_alarm},
  // 1S探测下自动切回时间
  {SM_CLOCK, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_YYMMDD, EV_1S, SM_CLOCK, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_YYMMDD, sm_clock_display_submod1},
  
  // 按mod0显示温度
  {SM_CLOCK, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_WEEK, EV_KEY_MOD_PRESS, SM_CLOCK, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_TEMP, sm_clock_display_submod3},
  // set0回到时分秒显示模式
  {SM_CLOCK, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_WEEK, EV_KEY_SET_PRESS, SM_CLOCK, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_HHMMSS, sm_clock_display_submod0},
  // 闹钟0响了
  {SM_CLOCK, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_WEEK, EV_ALARM0, SM_CLOCK, SM_CLOCK_ALARM<<4|SM_CLOCK_ALARM_HIT_ALARM0, sm_clock_alarm},
  // 闹钟1响了
  {SM_CLOCK, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_WEEK, EV_ALARM1, SM_CLOCK, SM_CLOCK_ALARM<<4|SM_CLOCK_ALARM_HIT_ALARM1, sm_clock_alarm},  
  // 1S探测下自动切回时间
  {SM_CLOCK, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_WEEK, EV_1S, SM_CLOCK, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_WEEK, sm_clock_display_submod2},  
  
  // 按mod0回到时分秒显示模式
  {SM_CLOCK, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_TEMP, EV_KEY_MOD_PRESS, SM_CLOCK, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_HHMMSS, sm_clock_display_submod0},
  // set0回到时分秒显示模式
  {SM_CLOCK, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_TEMP, EV_KEY_SET_PRESS, SM_CLOCK, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_HHMMSS, sm_clock_display_submod0},
  // 闹钟0响了
  {SM_CLOCK, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_TEMP, EV_ALARM0, SM_CLOCK, SM_CLOCK_ALARM<<4|SM_CLOCK_ALARM_HIT_ALARM0, sm_clock_alarm},
  // 闹钟1响了
  {SM_CLOCK, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_TEMP, EV_ALARM1, SM_CLOCK, SM_CLOCK_ALARM<<4|SM_CLOCK_ALARM_HIT_ALARM1, sm_clock_alarm},
  // 1S探测下自动切回时间
  {SM_CLOCK, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_TEMP, EV_1S, SM_CLOCK, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_TEMP, sm_clock_display_submod3},  
};

static const struct sm_trans code sm_trans_clock_mod_time[] = {
  /* SM_CLOCK_MODIFY_TIME */
  // 从别的状态进入，防止误操作
  {SM_CLOCK, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_INIT, EV_KEY_MOD_UP, SM_CLOCK, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_HH, sm_clock_mod_time_submod0}, 
  // 按mod0进入修改分钟模式
  {SM_CLOCK, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_HH, EV_KEY_MOD_PRESS, SM_CLOCK, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_MM, sm_clock_mod_time_submod1},
  // 按set0小时++并写入rtc
  {SM_CLOCK, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_HH, EV_KEY_SET_PRESS, SM_CLOCK, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_HH, sm_clock_mod_time_submod0},
  // set1小时连续++
  {SM_CLOCK, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_HH, EV_KEY_SET_LPRESS, SM_CLOCK, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_HH, sm_clock_mod_time_submod0},
  // set抬起停止++并写入rtc
  {SM_CLOCK, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_HH, EV_KEY_SET_UP, SM_CLOCK, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_HH, sm_clock_mod_time_submod0},
 // mod1 进入修改闹钟模式
  {SM_CLOCK, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_HH, EV_KEY_MOD_LPRESS, SM_CLOCK, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_INIT, sm_clock_mod_alarm_init},
  // mod0 进入修改秒模式
  {SM_CLOCK, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_MM, EV_KEY_MOD_PRESS, SM_CLOCK, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_SS, sm_clock_mod_time_submod2},
  // set0 分钟++并写入rtc
  {SM_CLOCK, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_MM, EV_KEY_SET_PRESS, SM_CLOCK, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_MM, sm_clock_mod_time_submod1},
  // set1 分钟持续++
  {SM_CLOCK, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_MM, EV_KEY_SET_LPRESS, SM_CLOCK, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_MM, sm_clock_mod_time_submod1},
  // set抬起停止++并写入rtc
  {SM_CLOCK, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_MM, EV_KEY_SET_UP, SM_CLOCK, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_MM, sm_clock_mod_time_submod1},
  // mod1 进入修改闹钟模式
  {SM_CLOCK, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_MM, EV_KEY_MOD_LPRESS, SM_CLOCK, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_INIT, sm_clock_mod_alarm_init},
  // mod0进入修改年模式
  {SM_CLOCK, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_SS, EV_KEY_MOD_PRESS, SM_CLOCK, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_YY, sm_clock_mod_time_submod3},
  // set0将秒清0并写入rtc
  {SM_CLOCK, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_SS, EV_KEY_SET_PRESS, SM_CLOCK, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_SS, sm_clock_mod_time_submod2},
  // mod1进入修改闹钟模式
  {SM_CLOCK, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_SS, EV_KEY_MOD_LPRESS, SM_CLOCK, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_INIT, sm_clock_mod_alarm_init},  
  // 按mod0进入修改月模式
  {SM_CLOCK, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_YY, EV_KEY_MOD_PRESS, SM_CLOCK, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_MO, sm_clock_mod_time_submod4},
  // set0 年++
  {SM_CLOCK, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_YY, EV_KEY_SET_PRESS, SM_CLOCK, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_YY, sm_clock_mod_time_submod3},
  // 长按set年持续++
  {SM_CLOCK, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_YY, EV_KEY_SET_LPRESS, SM_CLOCK, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_YY, sm_clock_mod_time_submod3},
  // 抬起set停止年++并写入rtc
  {SM_CLOCK, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_YY, EV_KEY_SET_UP, SM_CLOCK, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_YY, sm_clock_mod_time_submod3},
  // mod1 进入修改闹钟模式  
  {SM_CLOCK, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_YY, EV_KEY_MOD_LPRESS, SM_CLOCK, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_INIT, sm_clock_mod_alarm_init}, 
  // mod0 进入修改日模式
  {SM_CLOCK, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_MO, EV_KEY_MOD_PRESS, SM_CLOCK, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_DD, sm_clock_mod_time_submod5},
  // set0 月++
  {SM_CLOCK, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_MO, EV_KEY_SET_PRESS, SM_CLOCK, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_MO, sm_clock_mod_time_submod4},
  // 长按set 月持续++
  {SM_CLOCK, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_MO, EV_KEY_SET_LPRESS, SM_CLOCK, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_MO, sm_clock_mod_time_submod4}, 
  // 抬起set停止月++并写入rtc
  {SM_CLOCK, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_MO, EV_KEY_SET_UP, SM_CLOCK, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_MO, sm_clock_mod_time_submod4}, 
  // mod1 进入修改闹钟模式  
  {SM_CLOCK, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_MO, EV_KEY_MOD_LPRESS, SM_CLOCK, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_INIT, sm_clock_mod_alarm_init},   
  // mod0 进入修改小时模式
  {SM_CLOCK, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_DD, EV_KEY_MOD_PRESS, SM_CLOCK, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_HH, sm_clock_mod_time_submod0},
  // set0 日++
  {SM_CLOCK, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_DD, EV_KEY_SET_PRESS, SM_CLOCK, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_DD, sm_clock_mod_time_submod5},
  // set1 日持续++  
  {SM_CLOCK, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_DD, EV_KEY_SET_LPRESS, SM_CLOCK, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_DD, sm_clock_mod_time_submod5},
  // set抬起停止日++写入rtc  
  {SM_CLOCK, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_DD, EV_KEY_SET_UP, SM_CLOCK, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_DD, sm_clock_mod_time_submod5},
 // mod1 进入修改闹钟模式
  {SM_CLOCK, SM_CLOCK_MODIFY_TIME<<4|SM_CLOCK_MODIFY_TIME_DD, EV_KEY_MOD_LPRESS, SM_CLOCK, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_INIT, sm_clock_mod_alarm_init},
};

static const struct sm_trans code sm_trans_clock_mod_alarm[] = {
  /* SM_CLOCK_MODIFY_ALARM */
  // 从别的状态进入，防止误操作
  {SM_CLOCK, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_INIT, EV_KEY_MOD_UP, SM_CLOCK, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_HH, sm_clock_mod_alarm_submod0},
  // set0小时++  
  {SM_CLOCK, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_HH, EV_KEY_SET_PRESS, SM_CLOCK, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_HH, sm_clock_mod_alarm_submod0},
  // set1小时持续++
  {SM_CLOCK, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_HH, EV_KEY_SET_LPRESS, SM_CLOCK, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_HH, sm_clock_mod_alarm_submod0},
  // set抬起停止++，写入rtc
  {SM_CLOCK, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_HH, EV_KEY_SET_UP, SM_CLOCK, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_HH, sm_clock_mod_alarm_submod0},
  // mod0进入修改分钟模式
  {SM_CLOCK, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_HH, EV_KEY_MOD_PRESS, SM_CLOCK, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_MM, sm_clock_mod_alarm_submod1},

  // mod1进入修改时钟显示
  {SM_CLOCK, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_HH, EV_KEY_MOD_LPRESS, SM_CLOCK, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_INIT, sm_clock_display_init},
 
  
  // set0分钟++
  {SM_CLOCK, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_MM, EV_KEY_SET_PRESS, SM_CLOCK, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_MM, sm_clock_mod_alarm_submod1},
  // set1分钟持续++
  {SM_CLOCK, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_MM, EV_KEY_SET_LPRESS, SM_CLOCK, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_MM, sm_clock_mod_alarm_submod1}, 
  // set抬起停止++，写入rtc  
  {SM_CLOCK, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_MM, EV_KEY_SET_UP, SM_CLOCK, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_MM, sm_clock_mod_alarm_submod1}, 
  // mod0进入调整重复日状态
  {SM_CLOCK, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_MM, EV_KEY_MOD_PRESS, SM_CLOCK, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_DAY, sm_clock_mod_alarm_submod2}, 

  // set0调整打开关闭，并写入rtc
  {SM_CLOCK, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_DAY, EV_KEY_SET_PRESS, SM_CLOCK, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_DAY, sm_clock_mod_alarm_submod2},
  // mod0进入修改下一天状态
  {SM_CLOCK, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_DAY, EV_KEY_MOD_PRESS, SM_CLOCK, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_DAY, sm_clock_mod_alarm_submod2},
  // EV_KEY_V0进入修改整点报时
  {SM_CLOCK, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_DAY, EV_KEY_V0, SM_CLOCK, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_BS, sm_clock_mod_alarm_submod3},  
  
  // set0 调整打开关闭
  {SM_CLOCK, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_BS, EV_KEY_SET_PRESS, SM_CLOCK, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_BS, sm_clock_mod_alarm_submod3},
  // mod0进入修改MUSIC状态
  {SM_CLOCK, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_BS, EV_KEY_MOD_PRESS, SM_CLOCK, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_MUSIC, sm_clock_mod_alarm_submod4},
  
  // set0 调整music index并写入rtc
  {SM_CLOCK, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_MUSIC, EV_KEY_SET_PRESS, SM_CLOCK, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_MUSIC, sm_clock_mod_alarm_submod4},
  // mod0进入修改HH状态
  {SM_CLOCK, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_MUSIC, EV_KEY_MOD_PRESS, SM_CLOCK, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_INIT, sm_clock_mod_alarm_init},
  
  // mod1进入修改全局状态模式  
  {SM_CLOCK, SM_CLOCK_MODIFY_ALARM<<4|SM_CLOCK_MODIFY_ALARM_MUSIC, EV_KEY_MOD_LPRESS, SM_CLOCK, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_INIT, sm_clock_display_init}, 
};

  
static const struct sm_trans code sm_trans_clock_powersave[] = {
  /* SM_CLOCK_POWERSAVE */
  // 250ms后进入睡眠
  {SM_CLOCK, SM_CLOCK_POWERSAVE<<4|SM_CLOCK_POWERSAVE_INIT, EV_250MS, SM_CLOCK, SM_CLOCK_POWERSAVE<<4|SM_CLOCK_POWERSAVE_PS, sm_clock_powersave},
  // mod0回到时间显示模式 
  {SM_CLOCK, SM_CLOCK_POWERSAVE<<4|SM_CLOCK_POWERSAVE_PS, EV_KEY_MOD_PRESS, SM_CLOCK, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_HHMMSS, sm_clock_display_submod0},
  // set0回到时间显示模式
  {SM_CLOCK, SM_CLOCK_POWERSAVE<<4|SM_CLOCK_POWERSAVE_PS, EV_KEY_SET_PRESS, SM_CLOCK, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_HHMMSS, sm_clock_display_submod0},
  // 闹铃响了，唤醒吧
  {SM_CLOCK, SM_CLOCK_POWERSAVE<<4|SM_CLOCK_POWERSAVE_PS, EV_ALARM0, SM_CLOCK, SM_CLOCK_ALARM<<4|SM_CLOCK_ALARM_HIT_ALARM0, sm_clock_alarm},
  {SM_CLOCK, SM_CLOCK_POWERSAVE<<4|SM_CLOCK_POWERSAVE_PS, EV_ALARM1, SM_CLOCK, SM_CLOCK_ALARM<<4|SM_CLOCK_ALARM_HIT_ALARM1, sm_clock_alarm},
};  

static const struct sm_trans code sm_trans_clock_alarm[] = {  
  /* SM_CLOCK_ALARM */
  // mod0回到时间显示模式
  {SM_CLOCK, SM_CLOCK_ALARM<<4|SM_CLOCK_ALARM_HIT_ALARM0, EV_KEY_MOD_PRESS, SM_CLOCK, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_HHMMSS, sm_clock_display_submod0},
  // set0回到时间显示模式
  {SM_CLOCK, SM_CLOCK_ALARM<<4|SM_CLOCK_ALARM_HIT_ALARM0, EV_KEY_SET_PRESS, SM_CLOCK, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_HHMMSS, sm_clock_display_submod0}, 
  // mod0回到时间显示模式
  {SM_CLOCK, SM_CLOCK_ALARM<<4|SM_CLOCK_ALARM_HIT_ALARM1, EV_KEY_MOD_PRESS, SM_CLOCK, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_HHMMSS, sm_clock_display_submod0},
  // set0回到时间显示模式
  {SM_CLOCK, SM_CLOCK_ALARM<<4|SM_CLOCK_ALARM_HIT_ALARM1, EV_KEY_SET_PRESS, SM_CLOCK, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_HHMMSS, sm_clock_display_submod0}, 
  // 整点报时自动切换
  {SM_CLOCK, SM_CLOCK_ALARM<<4|SM_CLOCK_ALARM_HIT_ALARM1, EV_1S, SM_CLOCK, SM_CLOCK_ALARM<<4|SM_CLOCK_ALARM_HIT_ALARM1, sm_clock_alarm},
};

static const struct sm_trans code sm_trans_clock_timer[] = {  
  /* SM_CLOCK_TIMER */
  // 防止误操作
  {SM_CLOCK, SM_CLOCK_TIMER<<4|SM_CLOCK_TIMER_INIT, EV_KEY_SET_UP, SM_CLOCK, SM_CLOCK_TIMER<<4|SM_CLOCK_TIMER_CLEAR, sm_clock_timer_submod0},
  // set1进入倒计时器模式
  {SM_CLOCK, SM_CLOCK_TIMER<<4|SM_CLOCK_TIMER_CLEAR, EV_KEY_SET_LPRESS, SM_CLOCK, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_INIT, sm_clock_counter_init},
  // mod0跑表开始跑
  {SM_CLOCK, SM_CLOCK_TIMER<<4|SM_CLOCK_TIMER_CLEAR, EV_KEY_MOD_DOWN, SM_CLOCK, SM_CLOCK_TIMER<<4|SM_CLOCK_TIMER_RUNNING, sm_clock_timer_submod1}, 
  // set0计次
  {SM_CLOCK, SM_CLOCK_TIMER<<4|SM_CLOCK_TIMER_RUNNING, EV_KEY_SET_DOWN, SM_CLOCK, SM_CLOCK_TIMER<<4|SM_CLOCK_TIMER_RUNNING, sm_clock_timer_submod1},
  {SM_CLOCK, SM_CLOCK_TIMER<<4|SM_CLOCK_TIMER_RUNNING, EV_KEY_SET_UP, SM_CLOCK, SM_CLOCK_TIMER<<4|SM_CLOCK_TIMER_RUNNING, sm_clock_timer_submod1},  
  // mod0跑表停止  
  {SM_CLOCK, SM_CLOCK_TIMER<<4|SM_CLOCK_TIMER_RUNNING, EV_KEY_MOD_DOWN, SM_CLOCK, SM_CLOCK_TIMER<<4|SM_CLOCK_TIMER_STOP, sm_clock_timer_submod2},
  // mod0跑表清零
  {SM_CLOCK, SM_CLOCK_TIMER<<4|SM_CLOCK_TIMER_STOP, EV_KEY_MOD_DOWN, SM_CLOCK, SM_CLOCK_TIMER<<4|SM_CLOCK_TIMER_CLEAR, sm_clock_timer_submod0},
  // set0逐次显示计次
  {SM_CLOCK, SM_CLOCK_TIMER<<4|SM_CLOCK_TIMER_STOP, EV_KEY_SET_DOWN, SM_CLOCK, SM_CLOCK_TIMER<<4|SM_CLOCK_TIMER_STOP, sm_clock_timer_submod2},
  {SM_CLOCK, SM_CLOCK_TIMER<<4|SM_CLOCK_TIMER_STOP, EV_KEY_SET_UP, SM_CLOCK, SM_CLOCK_TIMER<<4|SM_CLOCK_TIMER_STOP, sm_clock_timer_submod2},  
};  

static const struct sm_trans code sm_trans_clock_counter[] = {  
  /* SM_CLOCK_COUNTER */
  // 防止误操作
  {SM_CLOCK, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_INIT, EV_KEY_SET_UP, SM_CLOCK, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_HH, sm_clock_counter_submod0},
  // mod0进入修改分钟状态
  {SM_CLOCK, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_HH, EV_KEY_MOD_PRESS, SM_CLOCK, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_MM, sm_clock_counter_submod1},
  // set0小时++
  {SM_CLOCK, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_HH, EV_KEY_SET_PRESS, SM_CLOCK, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_HH, sm_clock_counter_submod0},
  // set1小时快速++
  {SM_CLOCK, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_HH, EV_KEY_SET_LPRESS, SM_CLOCK, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_HH, sm_clock_counter_submod0}, 
  // set抬起小时快速++停止
  {SM_CLOCK, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_HH, EV_KEY_SET_UP, SM_CLOCK, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_HH, sm_clock_counter_submod0},   
  // mod1切回时间显示
  {SM_CLOCK, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_HH, EV_KEY_MOD_LPRESS, SM_CLOCK, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_INIT, sm_clock_display_init},
  // 每250ms刷新显示
  {SM_CLOCK, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_HH, EV_250MS, SM_CLOCK, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_HH, sm_clock_counter_submod0},
  // mod0进入修改秒状态
  {SM_CLOCK, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_MM, EV_KEY_MOD_PRESS, SM_CLOCK, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_SS, sm_clock_counter_submod2},
  // set0 分钟++
  {SM_CLOCK, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_MM, EV_KEY_SET_PRESS, SM_CLOCK, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_MM, sm_clock_counter_submod1},
  // set1 分钟快速++
  {SM_CLOCK, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_MM, EV_KEY_SET_LPRESS, SM_CLOCK, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_MM, sm_clock_counter_submod1},
  // set 抬起分钟快速++停止  
  {SM_CLOCK, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_MM, EV_KEY_SET_UP, SM_CLOCK, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_MM, sm_clock_counter_submod1},
  // mod1 回到时间显示  
  {SM_CLOCK, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_MM, EV_KEY_MOD_LPRESS, SM_CLOCK, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_INIT, sm_clock_display_init},  
  // 每250ms刷新显示
  {SM_CLOCK, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_MM, EV_250MS, SM_CLOCK, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_MM, sm_clock_counter_submod1},
  // mod0 开始倒计时
  {SM_CLOCK, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_SS, EV_KEY_MOD_PRESS, SM_CLOCK, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_RUNNING, sm_clock_counter_submod3},
  // set0 秒++
  {SM_CLOCK, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_SS, EV_KEY_SET_PRESS, SM_CLOCK, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_SS, sm_clock_counter_submod2},
  // set1 秒快速++
  {SM_CLOCK, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_SS, EV_KEY_SET_LPRESS, SM_CLOCK, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_SS, sm_clock_counter_submod2},
  // set抬起秒快速++停止
  {SM_CLOCK, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_SS, EV_KEY_SET_UP, SM_CLOCK, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_SS, sm_clock_counter_submod2},
  // mod1回到时间显示  
  {SM_CLOCK, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_SS, EV_KEY_MOD_LPRESS, SM_CLOCK, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_INIT, sm_clock_display_init},
  // 每250ms刷新显示
  {SM_CLOCK, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_SS, EV_250MS, SM_CLOCK, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_SS, sm_clock_counter_submod2},
  // set0 暂停倒计时
  {SM_CLOCK, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_RUNNING, EV_KEY_SET_PRESS, SM_CLOCK, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_PAUSE, sm_clock_counter_submod4}, 
  // set0 继续倒计时
  {SM_CLOCK, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_PAUSE, EV_KEY_SET_PRESS, SM_CLOCK, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_RUNNING, sm_clock_counter_submod3},
  // mod0 清除
  {SM_CLOCK, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_PAUSE, EV_KEY_MOD_PRESS, SM_CLOCK, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_HH, sm_clock_counter_submod0},
  // 倒计时结束，响铃
  {SM_CLOCK, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_RUNNING, EV_COUNTER, SM_CLOCK, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_STOP, sm_clock_counter_submod5},
  // mod0 停止响铃
  {SM_CLOCK, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_STOP, EV_KEY_MOD_PRESS, SM_CLOCK, SM_CLOCK_COUNTER<<4|SM_CLOCK_COUNTER_MODIFY_HH, sm_clock_counter_submod0},  
};

static const struct sm_trans code sm_trans_power_pack_display[] = {
  /* SM_POWER_PACK_DISPLAY */
  {SM_POWER_PACK, SM_POWER_PACK_DISPLAY<<4|SM_POWER_PACK_DISPLAY_INIT, EV_KEY_MOD_UP, SM_POWER_PACK, SM_POWER_PACK_DISPLAY<<4|SM_POWER_PACK_DISPLAY_POWER, sm_power_pack_display_submod0},
  {SM_POWER_PACK, SM_POWER_PACK_DISPLAY<<4|SM_POWER_PACK_DISPLAY_INIT, EV_KEY_SET_UP, SM_POWER_PACK, SM_POWER_PACK_DISPLAY<<4|SM_POWER_PACK_DISPLAY_POWER, sm_power_pack_display_submod0},
  {SM_POWER_PACK, SM_POWER_PACK_DISPLAY<<4|SM_POWER_PACK_DISPLAY_POWER, EV_KEY_SET_PRESS, SM_POWER_PACK, SM_POWER_PACK_DISPLAY<<4|SM_POWER_PACK_DISPLAY_POWER, sm_power_pack_display_submod0},
  {SM_POWER_PACK, SM_POWER_PACK_DISPLAY<<4|SM_POWER_PACK_DISPLAY_POWER, EV_KEY_MOD_LPRESS, SM_CLOCK, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_INIT, sm_clock_display_init},  
  {SM_POWER_PACK, SM_POWER_PACK_DISPLAY<<4|SM_POWER_PACK_DISPLAY_POWER, EV_KEY_SET_LPRESS, SM_POWER_PACK, SM_POWER_PACK_DISPLAY<<4|SM_POWER_PACK_DISPLAY_POWER, sm_power_pack_display_submod0},  
  {SM_POWER_PACK, SM_POWER_PACK_DISPLAY<<4|SM_POWER_PACK_DISPLAY_POWER, EV_KEY_MOD_SET_LPRESS, SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_INIT, sm_fuse_test_init},  
  {SM_POWER_PACK, SM_POWER_PACK_DISPLAY<<4|SM_POWER_PACK_DISPLAY_POWER, EV_1S, SM_POWER_PACK, SM_POWER_PACK_DISPLAY<<4|SM_POWER_PACK_DISPLAY_POWER, sm_power_pack_display_submod0},  
  {SM_POWER_PACK, SM_POWER_PACK_DISPLAY<<4|SM_POWER_PACK_DISPLAY_POWER, EV_POWER_SAVE, SM_POWER_PACK, SM_POWER_PACK_POWERSAVE<<4|SM_POWER_PACK_POWERSAVE_INIT, sm_power_pack_powersave_init},
};

static const struct sm_trans code sm_trans_power_pack_powersave[] = {
  {SM_POWER_PACK, SM_POWER_PACK_POWERSAVE<<4|SM_POWER_PACK_POWERSAVE_INIT, EV_250MS, SM_POWER_PACK, SM_POWER_PACK_POWERSAVE<<4|SM_POWER_PACK_POWERSAVE_SLEEP, sm_power_pack_powersave_submod0},
  {SM_POWER_PACK, SM_POWER_PACK_POWERSAVE<<4|SM_POWER_PACK_POWERSAVE_SLEEP, EV_KEY_SET_PRESS, SM_POWER_PACK, SM_POWER_PACK_DISPLAY<<4|SM_POWER_PACK_DISPLAY_POWER, sm_power_pack_display_submod0},
  {SM_POWER_PACK, SM_POWER_PACK_POWERSAVE<<4|SM_POWER_PACK_POWERSAVE_SLEEP, EV_KEY_MOD_PRESS, SM_POWER_PACK, SM_POWER_PACK_DISPLAY<<4|SM_POWER_PACK_DISPLAY_POWER, sm_power_pack_display_submod0},
};

static const struct sm_trans code sm_trans_fuse_test[] = {  
  /* SM_FUSE_TEST */
  {SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_INIT, EV_KEY_MOD_UP, SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_BROKE, sm_fuse_test_submod0},
  // set0启动测试
  {SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_BROKE, EV_KEY_SET_PRESS, SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_BROKE, sm_fuse_test_submod0},
  // 测试fuse0 broke 收到EV_FUSE0_BROKE, 更新测试结果
  {SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_BROKE, EV_FUSE0_BROKE, SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_BROKE, sm_fuse_test_submod0},
  // 测试fuse1 broke 收到EV_FUSE1_BROKE, 更新测试结果
  {SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_BROKE, EV_FUSE1_BROKE, SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_BROKE, sm_fuse_test_submod0},
  // 测试 tripwire broke EV_FUSE_TRIPWIRE, 更新测试结果
  {SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_BROKE, EV_FUSE_TRIPWIRE, SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_BROKE, sm_fuse_test_submod0},
  // 收到EV_1S，更新测试结果
  {SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_BROKE, EV_1S, SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_BROKE, sm_fuse_test_submod0},
  // mod0 切换到设置/测试THERMO HI
  {SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_BROKE, EV_KEY_MOD_PRESS, SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_THERMO_HI_SET, sm_fuse_test_submod1},
  // mod1 切换回时钟模式
  {SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_BROKE, EV_KEY_MOD_LPRESS, SM_CLOCK, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_INIT, sm_clock_display_init},

  // set1 切换到定时参数设置
  {SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_BROKE, EV_KEY_SET_LPRESS, SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_INIT, sm_fuse_param_init},
  // modset1 切换到全局参数设置
  {SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_BROKE, EV_KEY_MOD_SET_LPRESS, SM_GLOBAL_FLAG, SM_GLOBAL_FLAG_MODIFY<<4|SM_GLOBAL_FLAG_MODIFY_INIT, sm_global_flag_mod_init},
  
  
  // set0设置thermo hi参数
  {SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_THERMO_HI_SET, EV_KEY_SET_PRESS, SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_THERMO_HI_SET, sm_fuse_test_submod1},
  // set0设置thermo hi参数++
  {SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_THERMO_HI_SET, EV_KEY_SET_LPRESS, SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_THERMO_HI_SET, sm_fuse_test_submod1},
  // set0设置thermo hi参数++停止
  {SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_THERMO_HI_SET, EV_KEY_SET_UP, SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_THERMO_HI_SET, sm_fuse_test_submod1},
  // mod0切换到测试模式
  {SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_THERMO_HI_SET, EV_KEY_MOD_PRESS, SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_THERMO_HI, sm_fuse_test_submod2},
  // set0启动测试
  {SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_THERMO_HI, EV_KEY_SET_PRESS, SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_THERMO_HI, sm_fuse_test_submod2},
  // 收到EV_THERMO_HI，更新显示
  {SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_THERMO_HI, EV_THERMO_HI, SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_THERMO_HI, sm_fuse_test_submod2},
  // 收到EV_1S，更新状态
  {SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_THERMO_HI, EV_1S, SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_THERMO_HI, sm_fuse_test_submod2},
  // mod0 切换到设置thermo lo
  {SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_THERMO_HI, EV_KEY_MOD_PRESS, SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_THERMO_LO_SET, sm_fuse_test_submod3},
  
  // set0设置thermo lo参数
  {SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_THERMO_LO_SET, EV_KEY_SET_PRESS, SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_THERMO_LO_SET, sm_fuse_test_submod3},
  // set0设置thermo lo参数++
  {SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_THERMO_LO_SET, EV_KEY_SET_LPRESS, SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_THERMO_LO_SET, sm_fuse_test_submod1},
  // set0设置thermo lo参数++停止
  {SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_THERMO_LO_SET, EV_KEY_SET_UP, SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_THERMO_LO_SET, sm_fuse_test_submod1},
  // mod0切换到测试模式
  {SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_THERMO_LO_SET, EV_KEY_MOD_PRESS, SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_THERMO_LO, sm_fuse_test_submod4},
  // set0启动测试
  {SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_THERMO_LO, EV_KEY_SET_PRESS, SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_THERMO_LO, sm_fuse_test_submod4},
  // 收到EV_THERMO_LO，更新显示
  {SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_THERMO_LO, EV_THERMO_LO, SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_THERMO_LO, sm_fuse_test_submod4},
  // 收到EV_1S，更新状态
  {SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_THERMO_LO, EV_1S, SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_THERMO_LO, sm_fuse_test_submod4},
  // mod0 切换到测试 hg
  {SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_THERMO_LO, EV_KEY_MOD_PRESS, SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_HG_SET, sm_fuse_test_submod5},
 
  // set0调整ON/OFF
  {SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_HG_SET, EV_KEY_SET_PRESS, SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_HG_SET, sm_fuse_test_submod5},
  // mod0切换到测试模式
  {SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_HG_SET, EV_KEY_MOD_PRESS, SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_HG, sm_fuse_test_submod6},
  // set0启动测试
  {SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_HG, EV_KEY_SET_PRESS, SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_HG, sm_fuse_test_submod6},
  // 收到EV_ROTATE_HG，更新显示
  {SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_HG, EV_ROTATE_HG, SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_HG, sm_fuse_test_submod6},
  // 收到EV_1S，更新状态
  {SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_HG, EV_1S, SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_HG, sm_fuse_test_submod6},
  // mod0 切换到测试 mpu
  {SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_HG, EV_KEY_MOD_PRESS, SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_MPU_SET, sm_fuse_test_submod7},
  
  // set0敏感度+
  {SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_MPU_SET, EV_KEY_SET_PRESS, SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_MPU_SET, sm_fuse_test_submod7},
  // set0设置敏感度++
  {SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_MPU_SET, EV_KEY_SET_LPRESS, SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_MPU_SET, sm_fuse_test_submod7},
  // set0设置敏感度++停止
  {SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_MPU_SET, EV_KEY_SET_UP, SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_MPU_SET, sm_fuse_test_submod7},
  // mod0切换到测试模式
  {SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_MPU_SET, EV_KEY_MOD_PRESS, SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_MPU, sm_fuse_test_submod8},
  // set0启动测试
  {SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_MPU, EV_KEY_SET_PRESS, SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_MPU, sm_fuse_test_submod8},
  // 收到EV_MOT_MPU，更新显示
  {SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_MPU, EV_MOT_MPU, SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_MPU, sm_fuse_test_submod8}, 
  // 收到EV_1S，更新状态
  {SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_MPU, EV_1S, SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_MPU, sm_fuse_test_submod8},
  // mod0 切换到测试 remote
  {SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_MPU, EV_KEY_MOD_PRESS, SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_REMOTE_SET, sm_fuse_test_submod9},
  
  
  // set0调整ON/OFF
  {SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_REMOTE_SET, EV_KEY_SET_PRESS, SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_REMOTE_SET, sm_fuse_test_submod9},
  // mod0切换到测试模式
  {SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_REMOTE_SET, EV_KEY_MOD_PRESS, SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_REMOTE, sm_fuse_test_submod10},
  // set0启动测试
  {SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_REMOTE, EV_KEY_SET_PRESS, SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_REMOTE, sm_fuse_test_submod10},
  // 收到EV_REMOTE_ARM，更新显示
  {SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_REMOTE, EV_REMOTE_ARM, SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_REMOTE, sm_fuse_test_submod10},
  // 收到EV_REMOTE_DISARM，更新显示
  {SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_REMOTE, EV_REMOTE_DISARM, SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_REMOTE, sm_fuse_test_submod10},
  // 收到EV_REMOTE_DETONATE，更新显示
  {SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_REMOTE, EV_REMOTE_DETONATE, SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_REMOTE, sm_fuse_test_submod10},
  // 收到EV_1S，更新状态
  {SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_REMOTE, EV_1S, SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_REMOTE, sm_fuse_test_submod10},
  // mod0 切换到测试 fuse
  {SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_REMOTE, EV_KEY_MOD_PRESS, SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_BROKE, sm_fuse_test_submod0},
};


static const struct sm_trans code sm_trans_fuse_param[] = { 
  /* SM_FUSE_PARAM */
  {SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_INIT, EV_KEY_SET_UP, SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_YY, sm_fuse_param_submod0},
  // set0/1 调整年
  {SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_YY, EV_KEY_SET_PRESS, SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_YY, sm_fuse_param_submod0},
  {SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_YY, EV_KEY_SET_LPRESS, SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_YY, sm_fuse_param_submod0},
  {SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_YY, EV_KEY_SET_UP, SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_YY, sm_fuse_param_submod0},
  // mod0 切换调整时
  {SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_YY, EV_KEY_MOD_PRESS, SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_MO, sm_fuse_param_submod1},

  // mod1 进入ARM
  {SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_YY, EV_KEY_MOD_LPRESS, SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_INIT, sm_fuse_timer_init},
  // EV_REMOTE_ARM 进入ARM
  {SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_YY, EV_REMOTE_ARM, SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_INIT, sm_fuse_timer_init},
  
  // set0/1 调整月
  {SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_MO, EV_KEY_SET_PRESS, SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_MO, sm_fuse_param_submod1},
  {SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_MO, EV_KEY_SET_LPRESS, SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_MO, sm_fuse_param_submod1},
  {SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_MO, EV_KEY_SET_UP, SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_MO, sm_fuse_param_submod1},
  // mod0 切换调整时
  {SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_MO, EV_KEY_MOD_PRESS, SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_DD, sm_fuse_param_submod2},

  // set0/1 调整日
  {SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_DD, EV_KEY_SET_PRESS, SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_DD, sm_fuse_param_submod2},
  {SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_DD, EV_KEY_SET_LPRESS, SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_DD, sm_fuse_param_submod2},
  {SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_DD, EV_KEY_SET_UP, SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_DD, sm_fuse_param_submod2},
  // mod0 切换调整时
  {SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_DD, EV_KEY_MOD_PRESS, SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_HH, sm_fuse_param_submod3},
  // set0/1 调整时
  {SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_HH, EV_KEY_SET_PRESS, SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_HH, sm_fuse_param_submod3},
  {SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_HH, EV_KEY_SET_LPRESS, SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_HH, sm_fuse_param_submod3},
  {SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_HH, EV_KEY_SET_UP, SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_HH, sm_fuse_param_submod3},
  // mod0 切换调整分
  {SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_HH, EV_KEY_MOD_PRESS, SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_MM, sm_fuse_param_submod4},
  // set0/1 调整分
  {SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_MM, EV_KEY_SET_PRESS, SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_MM, sm_fuse_param_submod4},
  {SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_MM, EV_KEY_SET_LPRESS, SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_MM, sm_fuse_param_submod4},
  {SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_MM, EV_KEY_SET_UP, SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_MM, sm_fuse_param_submod4},
  // mod0 切换调整秒
  {SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_MM, EV_KEY_MOD_PRESS, SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_SS, sm_fuse_param_submod5},
  // set0/1 调整秒
  {SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_SS, EV_KEY_SET_PRESS, SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_SS, sm_fuse_param_submod5},
  {SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_SS, EV_KEY_SET_LPRESS, SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_SS, sm_fuse_param_submod5},
  {SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_SS, EV_KEY_SET_UP, SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_SS, sm_fuse_param_submod5},
  // mod0 切换调整password
  {SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_SS, EV_KEY_MOD_PRESS, SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_PASSWORD, sm_fuse_param_submod6},
  // set0 调整password 
  {SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_PASSWORD, EV_KEY_SET_PRESS, SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_PASSWORD, sm_fuse_param_submod6},
  {SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_PASSWORD, EV_KEY_SET_LPRESS, SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_PASSWORD, sm_fuse_param_submod6},
  {SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_PASSWORD, EV_KEY_SET_UP, SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_PASSWORD, sm_fuse_param_submod6},  
  // mod0 下一数字
  {SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_PASSWORD, EV_KEY_MOD_PRESS, SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_PASSWORD, sm_fuse_param_submod6}, 
  // 结尾从头开始
  {SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_PASSWORD, EV_KEY_V0, SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_YY, sm_fuse_param_submod0},  
  // set1 跳转fuse_timer
  {SM_FUSE, SM_FUSE_PARAM<<4|SM_FUSE_PARAM_PASSWORD, EV_KEY_MOD_LPRESS, SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_INIT, sm_fuse_timer_init},
};

static const struct sm_trans code sm_trans_fuse_timer[] = { 
  /* SM_FUSE_TIMER */ 
  // 过1秒进入prearmed状态
  {SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_INIT, EV_KEY_MOD_UP, SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_PREARMED, sm_fuse_timer_submod0},
  // 启动传感器
  {SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_PREARMED, EV_1S, SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_PREARMED, sm_fuse_timer_submod0}, 
  // 启动传感器，准备干活了
  {SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_PREARMED, EV_KEY_V1, SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_ARMED, sm_fuse_timer_submod1},
  // 启动传感器不成功，进入电路测试
  {SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_PREARMED, EV_KEY_V0, SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_INIT, sm_fuse_test_init},
  // 计时器时间到,回滚
  {SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_PREARMED, EV_COUNTER, SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_PREARMED, sm_fuse_timer_submod0},
  // fuse0剪断,回滚
  {SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_PREARMED, EV_FUSE0_BROKE, SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_PREARMED, sm_fuse_timer_submod0},
  // fuse1剪断,回滚
  {SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_PREARMED, EV_FUSE1_BROKE, SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_PREARMED, sm_fuse_timer_submod0},
  // 姿态变化,回滚
  {SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_PREARMED, EV_MOT_MPU, SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_PREARMED, sm_fuse_timer_submod0},
  // 姿态变化,回滚
  {SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_PREARMED, EV_ROTATE_HG, SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_PREARMED, sm_fuse_timer_submod0},
  // tripwire断,回滚
  {SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_PREARMED, EV_FUSE_TRIPWIRE, SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_PREARMED, sm_fuse_timer_submod0}, 
  // tripwire断,回滚
  {SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_PREARMED, EV_THERMO_HI, SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_PREARMED, sm_fuse_timer_submod0}, 
  // tripwire断,回滚
  {SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_PREARMED, EV_THERMO_LO, SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_PREARMED, sm_fuse_timer_submod0}, 
  // EV_REMOTE_ARM, 回滚
  {SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_PREARMED, EV_REMOTE_ARM, SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_PREARMED, sm_fuse_timer_submod0},
   // EV_REMOTE_DISARM, 回滚
  {SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_PREARMED, EV_REMOTE_DISARM, SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_PREARMED, sm_fuse_timer_submod0},
  // EV_REMOTE_DETONATE, 回滚
  {SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_PREARMED, EV_REMOTE_DETONATE, SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_PREARMED, sm_fuse_timer_submod0},
  
  // 测试是否进入超时节电
  {SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_ARMED, EV_1S, SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_ARMED, sm_fuse_timer_submod1},
  // set0在显示日期和hhmmss之间来回切换
  {SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_ARMED, EV_KEY_SET_PRESS, SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_ARMED, sm_fuse_timer_submod1},
  // mod0 进入密码验证
  {SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_ARMED, EV_KEY_MOD_PRESS, SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_VERIFY, sm_fuse_timer_submod2}, 
  // set0修改数字
  {SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_VERIFY, EV_KEY_SET_PRESS, SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_VERIFY, sm_fuse_timer_submod2},
  // mod0 下一数字
  {SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_VERIFY, EV_KEY_MOD_PRESS, SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_VERIFY, sm_fuse_timer_submod2}, 
  // EV_REMOTE_DISARM 解除
  {SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_VERIFY, EV_REMOTE_DISARM, SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_VERIFY, sm_fuse_timer_submod2}, 
  // 验证OK,解除，进入disarmed状态
  {SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_VERIFY, EV_KEY_V0, SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_DISARMED, sm_fuse_timer_submod3},
  // disarmed状态清除完毕，进入电路测试
  {SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_DISARMED, EV_KEY_V0, SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_INIT, sm_fuse_test_init}, 
  // 一次验证失败，返回倒计时
  {SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_VERIFY, EV_KEY_V1, SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_ARMED, sm_fuse_timer_submod1},
  // set1 撤销输入密码,返回倒计时  
  {SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_VERIFY, EV_KEY_SET_LPRESS, SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_ARMED, sm_fuse_timer_submod1},  
  // EV_1S 反超时耗电攻击
  {SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_VERIFY, EV_1S, SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_VERIFY, sm_fuse_timer_submod2},  

  // 三次验证失败,触发
  {SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_VERIFY, EV_KEY_V2, SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_PREDETONATE, sm_fuse_timer_submod4},
  // 计时器时间到,触发
  {SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_VERIFY, EV_COUNTER, SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_PREDETONATE, sm_fuse_timer_submod4},
  // fuse0剪断,触发
  {SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_VERIFY, EV_FUSE0_BROKE, SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_PREDETONATE, sm_fuse_timer_submod4},
  // fuse1剪断,触发
  {SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_VERIFY, EV_FUSE1_BROKE, SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_PREDETONATE, sm_fuse_timer_submod4},
  // 姿态变化,触发
  {SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_VERIFY, EV_MOT_MPU, SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_PREDETONATE, sm_fuse_timer_submod4},
  // 姿态变化,触发
  {SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_VERIFY, EV_ROTATE_HG, SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_PREDETONATE, sm_fuse_timer_submod4},
 // 温度太高,触发
  {SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_VERIFY, EV_THERMO_HI, SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_PREDETONATE, sm_fuse_timer_submod4},
  // 温度太低,触发
  {SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_VERIFY, EV_THERMO_LO, SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_PREDETONATE, sm_fuse_timer_submod4},
  // tripwire剪断,触发
  {SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_VERIFY, EV_FUSE_TRIPWIRE, SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_PREDETONATE, sm_fuse_timer_submod4},
  // EV_REMOTE_DETONATE, 触发
  {SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_VERIFY, EV_REMOTE_DETONATE, SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_PREDETONATE, sm_fuse_timer_submod4}, 
  // 计时器时间到,触发
  {SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_ARMED, EV_COUNTER, SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_PREDETONATE, sm_fuse_timer_submod4},
  // fuse0剪断,触发
  {SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_ARMED, EV_FUSE0_BROKE, SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_PREDETONATE, sm_fuse_timer_submod4},
  // fuse1剪断,触发
  {SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_ARMED, EV_FUSE1_BROKE, SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_PREDETONATE, sm_fuse_timer_submod4},
  // 姿态变化,触发
  {SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_ARMED, EV_MOT_MPU, SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_PREDETONATE, sm_fuse_timer_submod4},
  // 姿态变化,触发
  {SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_ARMED, EV_ROTATE_HG, SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_PREDETONATE, sm_fuse_timer_submod4},
 // 温度太高,触发
  {SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_ARMED, EV_THERMO_HI, SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_PREDETONATE, sm_fuse_timer_submod4},
  // 温度太低,触发
  {SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_ARMED, EV_THERMO_LO, SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_PREDETONATE, sm_fuse_timer_submod4},
  // tripwire剪断,触发
  {SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_ARMED, EV_FUSE_TRIPWIRE, SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_PREDETONATE, sm_fuse_timer_submod4},
  // EV_REMOTE_DETONATE, 触发
  {SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_ARMED, EV_REMOTE_DETONATE, SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_PREDETONATE, sm_fuse_timer_submod4},
  // EV_REMOTE_DISARM 解除
  {SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_ARMED, EV_REMOTE_DISARM, SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_DISARMED, sm_fuse_timer_submod3},

  // 关闭传感器完毕,进入detonate
  {SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_PREDETONATE, EV_KEY_V0, SM_FUSE, SM_FUSE_DETONATE<<4|SM_FUSE_DETONATE_INIT, sm_fuse_detonate_init},
  
  // 超时，进入节电
  {SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_ARMED, EV_POWER_SAVE, SM_FUSE, SM_FUSE_POWERSAVE<<4|SM_FUSE_POWERSAVE_INIT, sm_fuse_powersave_init},
};

static const struct sm_trans code sm_trans_fuse_detonate[] = {
  /* SM_FUSE_DETONATE */
  // 过250ms进入charge状态
  {SM_FUSE, SM_FUSE_DETONATE<<4|SM_FUSE_DETONATE_INIT, EV_250MS, SM_FUSE, SM_FUSE_DETONATE<<4|SM_FUSE_DETONATE_CHARGE, sm_fuse_detonate_submod0},
  // 持续charge 30秒
  {SM_FUSE, SM_FUSE_DETONATE<<4|SM_FUSE_DETONATE_CHARGE, EV_1S, SM_FUSE, SM_FUSE_DETONATE<<4|SM_FUSE_DETONATE_CHARGE, sm_fuse_detonate_submod0},
  // 通电状态，mod0进入电路测试
  {SM_FUSE, SM_FUSE_DETONATE<<4|SM_FUSE_DETONATE_CHARGE, EV_KEY_MOD_PRESS, SM_FUSE, SM_FUSE_DETONATE<<4|SM_FUSE_DETONATE_CHARGE, sm_fuse_detonate_submod0},
  // 通电状态，set0进入电路测试
  {SM_FUSE, SM_FUSE_DETONATE<<4|SM_FUSE_DETONATE_CHARGE, EV_KEY_SET_PRESS, SM_FUSE, SM_FUSE_DETONATE<<4|SM_FUSE_DETONATE_CHARGE, sm_fuse_detonate_submod0},
  // 通电满30S
  {SM_FUSE, SM_FUSE_DETONATE<<4|SM_FUSE_DETONATE_CHARGE, EV_KEY_V0, SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_INIT, sm_fuse_test_init},
};

static const struct sm_trans code sm_trans_fuse_powersave[] = {
  /* SM_FUSE_POWERSAVE */
  // 过250ms进入powersave
  {SM_FUSE, SM_FUSE_POWERSAVE<<4|SM_FUSE_POWERSAVE_INIT, EV_250MS, SM_FUSE, SM_FUSE_POWERSAVE<<4|SM_FUSE_POWERSAVE_PS, sm_fuse_powersave_submod0},
  // set0 回到 SM_FUSE_TIMER
  {SM_FUSE, SM_FUSE_POWERSAVE<<4|SM_FUSE_POWERSAVE_PS, EV_KEY_SET_PRESS, SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_ARMED, sm_fuse_timer_submod1},
  // mod0 回到 SM_FUSE_TIMER
  {SM_FUSE, SM_FUSE_POWERSAVE<<4|SM_FUSE_POWERSAVE_PS, EV_KEY_MOD_PRESS, SM_FUSE, SM_FUSE_TIMER<<4|SM_FUSE_TIMER_ARMED, sm_fuse_timer_submod1},  
  // 计时器时间到,触发
  {SM_FUSE, SM_FUSE_POWERSAVE<<4|SM_FUSE_POWERSAVE_PS, EV_COUNTER, SM_FUSE, SM_FUSE_POWERSAVE<<4|SM_FUSE_POWERSAVE_PREDETONATE, sm_fuse_powersave_submod1},
  // fuse0剪断,触发
  {SM_FUSE, SM_FUSE_POWERSAVE<<4|SM_FUSE_POWERSAVE_PS, EV_FUSE0_BROKE, SM_FUSE, SM_FUSE_POWERSAVE<<4|SM_FUSE_POWERSAVE_PREDETONATE, sm_fuse_powersave_submod1},
  // fuse1剪断,触发
  {SM_FUSE, SM_FUSE_POWERSAVE<<4|SM_FUSE_POWERSAVE_PS, EV_FUSE1_BROKE, SM_FUSE, SM_FUSE_POWERSAVE<<4|SM_FUSE_POWERSAVE_PREDETONATE, sm_fuse_powersave_submod1},
  // 姿态变化,触发
  {SM_FUSE, SM_FUSE_POWERSAVE<<4|SM_FUSE_POWERSAVE_PS, EV_MOT_MPU, SM_FUSE, SM_FUSE_POWERSAVE<<4|SM_FUSE_POWERSAVE_PREDETONATE, sm_fuse_powersave_submod1},
  // 姿态变化,触发
  {SM_FUSE, SM_FUSE_POWERSAVE<<4|SM_FUSE_POWERSAVE_PS, EV_ROTATE_HG,SM_FUSE,  SM_FUSE_POWERSAVE<<4|SM_FUSE_POWERSAVE_PREDETONATE, sm_fuse_powersave_submod1},
 // 温度太高,触发
  {SM_FUSE, SM_FUSE_POWERSAVE<<4|SM_FUSE_POWERSAVE_PS, EV_THERMO_HI, SM_FUSE, SM_FUSE_POWERSAVE<<4|SM_FUSE_POWERSAVE_PREDETONATE, sm_fuse_powersave_submod1},
  // 温度太低,触发
  {SM_FUSE, SM_FUSE_POWERSAVE<<4|SM_FUSE_POWERSAVE_PS, EV_THERMO_LO, SM_FUSE, SM_FUSE_POWERSAVE<<4|SM_FUSE_POWERSAVE_PREDETONATE, sm_fuse_powersave_submod1},
  // tripwire剪断,触发
  {SM_FUSE, SM_FUSE_POWERSAVE<<4|SM_FUSE_POWERSAVE_PS, EV_FUSE_TRIPWIRE, SM_FUSE, SM_FUSE_POWERSAVE<<4|SM_FUSE_POWERSAVE_PREDETONATE, sm_fuse_powersave_submod1},
  // EV_REMOTE_DETONATE，触发
  {SM_FUSE, SM_FUSE_POWERSAVE<<4|SM_FUSE_POWERSAVE_PS, EV_REMOTE_DETONATE, SM_FUSE, SM_FUSE_POWERSAVE<<4|SM_FUSE_POWERSAVE_PREDETONATE, sm_fuse_powersave_submod1},
  // EV_REMOTE_DISARM，解除
  {SM_FUSE, SM_FUSE_POWERSAVE<<4|SM_FUSE_POWERSAVE_PS, EV_REMOTE_DISARM, SM_FUSE, SM_FUSE_POWERSAVE<<4|SM_FUSE_POWERSAVE_DISARM, sm_fuse_powersave_submod2},
  // 进入detonate
  {SM_FUSE, SM_FUSE_POWERSAVE<<4|SM_FUSE_POWERSAVE_PREDETONATE, EV_KEY_V0, SM_FUSE, SM_FUSE_DETONATE<<4|SM_FUSE_DETONATE_INIT, sm_fuse_detonate_init},
  // 进入fuse test
  {SM_FUSE, SM_FUSE_POWERSAVE<<4|SM_FUSE_POWERSAVE_DISARM, EV_KEY_V0, SM_FUSE, SM_FUSE_TEST<<4|SM_FUSE_TEST_INIT, sm_fuse_test_init},
  
};  

static const struct sm_trans code sm_trans_global_flag_mod[] = {
  /* SM_CLOCK_MODIFY_GLOBAL_FLAG */
  // 防止误操作
  {SM_GLOBAL_FLAG, SM_GLOBAL_FLAG_MODIFY<<4|SM_GLOBAL_FLAG_MODIFY_INIT, EV_KEY_MOD_UP, SM_GLOBAL_FLAG, SM_GLOBAL_FLAG_MODIFY<<4|SM_GLOBAL_FLAG_MODIFY_PS, sm_global_flag_mod_submod0},
  // set0 省电模式超时时间设置
  {SM_GLOBAL_FLAG, SM_GLOBAL_FLAG_MODIFY<<4|SM_GLOBAL_FLAG_MODIFY_PS, EV_KEY_SET_PRESS, SM_GLOBAL_FLAG, SM_GLOBAL_FLAG_MODIFY<<4|SM_GLOBAL_FLAG_MODIFY_PS, sm_global_flag_mod_submod0},
  // mod0 进入按键音ON/OFF设置
  {SM_GLOBAL_FLAG, SM_GLOBAL_FLAG_MODIFY<<4|SM_GLOBAL_FLAG_MODIFY_PS, EV_KEY_MOD_PRESS, SM_GLOBAL_FLAG, SM_GLOBAL_FLAG_MODIFY<<4|SM_GLOBAL_FLAG_MODIFY_BEEP, sm_global_flag_mod_submod1},  

  // mod1进入显示时间状态
  {SM_GLOBAL_FLAG, SM_GLOBAL_FLAG_MODIFY<<4|SM_GLOBAL_FLAG_MODIFY_PS, EV_KEY_MOD_LPRESS, SM_CLOCK, SM_CLOCK_DISPLAY<<4|SM_CLOCK_DISPLAY_INIT, sm_clock_display_init},

  // set0 按键音ON/OFF
  {SM_GLOBAL_FLAG, SM_GLOBAL_FLAG_MODIFY<<4|SM_GLOBAL_FLAG_MODIFY_BEEP, EV_KEY_SET_PRESS, SM_GLOBAL_FLAG, SM_GLOBAL_FLAG_MODIFY<<4|SM_GLOBAL_FLAG_MODIFY_BEEP, sm_global_flag_mod_submod1}, 
  // mod0 闹铃时间调整
  {SM_GLOBAL_FLAG, SM_GLOBAL_FLAG_MODIFY<<4|SM_GLOBAL_FLAG_MODIFY_BEEP, EV_KEY_MOD_PRESS, SM_GLOBAL_FLAG, SM_GLOBAL_FLAG_MODIFY<<4|SM_GLOBAL_FLAG_MODIFY_MUSIC_TO, sm_global_flag_mod_submod2}, 

  // set0 闹铃时间调整
  {SM_GLOBAL_FLAG, SM_GLOBAL_FLAG_MODIFY<<4|SM_GLOBAL_FLAG_MODIFY_MUSIC_TO, EV_KEY_SET_PRESS, SM_GLOBAL_FLAG, SM_GLOBAL_FLAG_MODIFY<<4|SM_GLOBAL_FLAG_MODIFY_MUSIC_TO, sm_global_flag_mod_submod2}, 
 // mod0 进入1224小时设置状态
  {SM_GLOBAL_FLAG, SM_GLOBAL_FLAG_MODIFY<<4|SM_GLOBAL_FLAG_MODIFY_MUSIC_TO, EV_KEY_MOD_PRESS, SM_GLOBAL_FLAG, SM_GLOBAL_FLAG_MODIFY<<4|SM_GLOBAL_FLAG_MODIFY_1224, sm_global_flag_mod_submod3}, 

  
  // set0 1224模式切换
  {SM_GLOBAL_FLAG, SM_GLOBAL_FLAG_MODIFY<<4|SM_GLOBAL_FLAG_MODIFY_1224, EV_KEY_SET_PRESS, SM_GLOBAL_FLAG, SM_GLOBAL_FLAG_MODIFY<<4|SM_GLOBAL_FLAG_MODIFY_1224, sm_global_flag_mod_submod3},
  // mod0 进入设置省电模式状态
  {SM_GLOBAL_FLAG, SM_GLOBAL_FLAG_MODIFY<<4|SM_GLOBAL_FLAG_MODIFY_1224, EV_KEY_MOD_PRESS, SM_GLOBAL_FLAG, SM_GLOBAL_FLAG_MODIFY<<4|SM_GLOBAL_FLAG_MODIFY_PS, sm_global_flag_mod_submod0}, 
};

struct sm_trans_group
{
  struct sm_trans * table;
  unsigned char cnt;
};


static const struct sm_trans_group code sm_group_clock[] = {
  {sm_trans_clock_display, sizeof(sm_trans_clock_display)/ sizeof(struct sm_trans)},
  {sm_trans_clock_mod_time,sizeof(sm_trans_clock_mod_time)/ sizeof(struct sm_trans)},
  {sm_trans_clock_mod_alarm,sizeof(sm_trans_clock_mod_alarm)/ sizeof(struct sm_trans)},
  {sm_trans_clock_powersave,sizeof(sm_trans_clock_powersave)/ sizeof(struct sm_trans)},
  {sm_trans_clock_alarm,sizeof(sm_trans_clock_alarm)/ sizeof(struct sm_trans)},
  {sm_trans_clock_timer,sizeof(sm_trans_clock_timer)/ sizeof(struct sm_trans)},
  {sm_trans_clock_counter,sizeof(sm_trans_clock_counter)/ sizeof(struct sm_trans)},
};

static const struct sm_trans_group code sm_group_power_pack[] = {
  {sm_trans_power_pack_display, sizeof(sm_trans_power_pack_display)/ sizeof(struct sm_trans)},
  {sm_trans_power_pack_powersave, sizeof(sm_trans_power_pack_powersave)/ sizeof(struct sm_trans)},
};

static const struct sm_trans_group code sm_group_fuse[] = {
  {sm_trans_fuse_test,sizeof(sm_trans_fuse_test)/ sizeof(struct sm_trans)},
  {sm_trans_fuse_param,sizeof(sm_trans_fuse_param)/ sizeof(struct sm_trans)},
  {sm_trans_fuse_timer,sizeof(sm_trans_fuse_timer)/ sizeof(struct sm_trans)},
  {sm_trans_fuse_detonate,sizeof(sm_trans_fuse_detonate)/ sizeof(struct sm_trans)},
  {sm_trans_fuse_powersave,sizeof(sm_trans_fuse_powersave)/ sizeof(struct sm_trans)},
};

static const struct sm_trans_group code sm_group_global_flag[] = {
  {sm_trans_global_flag_mod, sizeof(sm_trans_global_flag_mod)/ sizeof(struct sm_trans)},
};

static const struct sm_trans_group * code sm_trans_table[] = {
  sm_group_clock,
  sm_group_power_pack,
  sm_group_fuse,
  sm_group_global_flag
};


struct sm_state_names
{
  const char * state_name;
  const char ** sub_state_names;
};

struct sm_table_names
{
  const char * table_name;
  struct sm_state_names * state_names;
};


static const struct sm_state_names code sm_clock_names[] = 
{
  {"SM_CLOCK_DISPLAY", sm_clock_display_ss_name},
  {"SM_CLOCK_MODIFY_TIME", sm_clock_mod_time_name},
  {"SM_CLOCK_MODIFY_ALARM", sm_clock_mod_alarm_ss_name},
  {"SM_CLOCK_POWERSAVE", sm_clock_powersave_ss_name},
  {"SM_CLOCK_ALARM", sm_clock_alarm_ss_name},
  {"SM_CLOCK_TIMER", sm_clock_timer_ss_name},
  {"SM_CLOCK_COUNTER", sm_clock_counter_ss_name},
  {NULL, NULL}
};

static const struct sm_state_names code sm_fuse_names[] = 
{
  {"SM_FUSE_TEST",sm_fuse_test_ss_name},
  {"SM_FUSE_PARAM",sm_fuse_param_ss_name},
  {"SM_FUSE_TIMER",sm_fuse_timer_ss_name},
  {"SM_FUSE_DETONATE",sm_fuse_detonate_ss_name},
  {"SM_FUSE_POWERSAVE",sm_fuse_powersave_ss_name},
  {NULL, NULL}
};

static const struct sm_state_names code sm_global_flag_names[] = {
  {"SM_GLOBAL_FLAG_MODIFY", sm_global_flag_mod_ss_name}, 
  {NULL, NULL}
};

static const struct sm_state_names code sm_power_pack_names[] = {
  {"SM_POWER_PACK_DISPLAY", sm_power_pack_display_ss_name}, 
  {"SM_POWER_PACK_POWERSAVE", sm_power_pack_powersave_ss_name},   
  {NULL, NULL}
};

static const struct sm_table_names code sm_names[] = 
{
  {"SM_CLOCK", sm_clock_names},
  {"SM_POWER_PACK", sm_power_pack_names},
  {"SM_FUSE", sm_fuse_names},
  {"SM_GLOBAL_FLAG", sm_global_flag_names},  
  {NULL, NULL}
};

static unsigned char sm_state;  // curent state hi 4 bits : state, lo 4 bits: sub-state 
unsigned char sm_curr_table; // current table
unsigned char sm_new_table; // new table

/* 不做任何过滤 */
void null_proc(enum task_events ev)
{
  run_state_machine(ev);
}

void run_state_machine(enum task_events ev)
{
  unsigned char c;
  unsigned char newstate;
  unsigned char index;
  
  index = get_sm_state(sm_state);
  for (c = 0 ; c < sm_trans_table[sm_curr_table][index].cnt ; c++) {
    if(ev == sm_trans_table[sm_curr_table][index].table[c].event 
      && sm_state == sm_trans_table[sm_curr_table][index].table[c].from_state
      && sm_curr_table == sm_trans_table[sm_curr_table][index].table[c].from_table) {
      newstate = sm_trans_table[sm_curr_table][index].table[c].to_state;
      sm_new_table = sm_trans_table[sm_curr_table][index].table[c].to_table;
      CDBG("SM [%s] [%s][%s][%s] -> [%s][%s][%s]\n",
        task_name[ev], 
        sm_names[sm_curr_table].table_name,
        sm_names[sm_curr_table].state_names[index].state_name, 
        sm_names[sm_curr_table].state_names[index].sub_state_names[get_sm_ss_state(sm_state)],
        sm_names[sm_new_table].table_name,
        sm_names[sm_new_table].state_names[get_sm_state(newstate)].state_name, 
        sm_names[sm_new_table].state_names[get_sm_state(newstate)].sub_state_names[get_sm_ss_state(newstate)]
        );
      sm_trans_table[sm_curr_table][index].table[c].sm_proc(sm_state, newstate, ev);
      sm_state = newstate;
      sm_curr_table = sm_new_table;
      break;
    }
  }
  
}


void sm_initialize (void) 
{
  CDBG("sm_initialize\n");
  sm_state = SM_CLOCK_DISPLAY|SM_CLOCK_DISPLAY_INIT;
  sm_curr_table = SM_CLOCK;
  
  lt_timer_switch_off();
  alarm_switch_on();
  rtc_set_lt_timer(0);

  set_task(EV_KEY_MOD_UP);
}

void sm_show_current(void)
{
    printf("current : [%s][%s][%s]\n", 
      sm_names[sm_curr_table].table_name, 
      sm_names[sm_curr_table].state_names[get_sm_state(sm_state)].state_name,
      sm_names[sm_curr_table].state_names[get_sm_state(sm_state)].sub_state_names[get_sm_ss_state(sm_state)]);
}


void sm_dump(void)
{
  char i,j,k;
  
  for(i = 0; sm_names[i].table_name != NULL; i++) {
    printf("%c table %s:\n", i == sm_curr_table ? '*' : ' ', sm_names[i]);
    for(j = 0; sm_names[i].state_names[j].state_name != NULL; j ++) {
      printf("  |--%c state %s:\n", i == sm_curr_table && j == get_sm_state(sm_state) ? '*' : ' ', sm_names[i].state_names[j].state_name);
      for(k = 0 ; sm_names[i].state_names[j].sub_state_names[k] != NULL ; k ++) {
        printf("  |   |--%c sub-state %s\n", i == sm_curr_table && j == get_sm_state(sm_state) && k == get_sm_ss_state(sm_state) ? '*' : ' ', 
          sm_names[i].state_names[j].sub_state_names[k]);
      }
    }
  }
}

void sm_dump_table(void)
{
  char i;
  for(i = 0; sm_names[i].table_name != NULL; i++) {
    printf("%c table %s\n", i == sm_curr_table ? '*' : ' ', sm_names[i]);
  }
}

void sm_dump_state(void)
{
  char i;
  for(i = 0; sm_names[sm_curr_table].state_names[i].state_name != NULL; i ++) {
    printf("%c state %s\n", i == get_sm_state(sm_state) ? '*' : ' ', sm_names[sm_curr_table].state_names[i].state_name);
  }
}

void sm_dump_sub_state(void)
{
  char i;
  for(i = 0 ; sm_names[sm_curr_table].state_names[get_sm_state(sm_state)].sub_state_names[i] != NULL ; i ++) {
    printf("%c sub-state %s\n", i == get_sm_ss_state(sm_state) ? '*' : ' ', 
      sm_names[sm_curr_table].state_names[get_sm_state(sm_state)].sub_state_names[i]);
  }
}


bit sm_set_table_by_name(const char * table_name)
{
  char i;
  for(i = 0; sm_names[i].table_name != NULL; i++) {
    if(strcmp(sm_names[i].table_name, table_name) == 0) {
      printf("table %s -> %s\n", sm_names[sm_curr_table].table_name, table_name);
      printf("state %s -> %s\n", 
        sm_names[sm_curr_table].state_names[get_sm_state(sm_state)].state_name,
        sm_names[i].state_names[0].state_name
        );
      printf("sub-state %s -> %s\n", 
        sm_names[sm_curr_table].state_names[get_sm_state(sm_state)].sub_state_names[get_sm_ss_state(sm_state)],
        sm_names[i].state_names[0].sub_state_names[0]
        );
      sm_curr_table = sm_new_table = i;
      sm_state = 0;
      return 0;
    }
  }
  return 1;
}

static void sm_set_state(unsigned char state)
{
  sm_state &= 0x0F; // remove state
  sm_state |= (state & 0x0F) << 4;
}

static void sm_set_sub_state(unsigned char sub_state)
{
  sm_state &= 0xF0; // remove sub-state
  sm_state |= sub_state & 0x0F;
}

bit sm_set_state_by_name(const char * state_name)
{
  char i;
  for(i = 0; sm_names[sm_curr_table].state_names[i].state_name != NULL; i ++) {
    if(strcmp(state_name, sm_names[sm_curr_table].state_names[i].state_name) == 0) {
      printf("state %s  -> %s\n", 
        sm_names[sm_curr_table].state_names[get_sm_state(sm_state)].state_name, 
        sm_names[sm_curr_table].state_names[i].state_name);
      printf("sub-state %s -> %s\n", 
        sm_names[sm_curr_table].state_names[get_sm_state(sm_state)].sub_state_names[get_sm_ss_state(sm_state)],
        sm_names[sm_curr_table].state_names[i].sub_state_names[0]
        );
      sm_set_state(i);
      sm_set_sub_state(0);
      return 0;
    }
  }
  return 1;
}

bit sm_set_sub_state_by_name(const char * sub_state_name)
{
  char i;
  for(i = 0 ; sm_names[sm_curr_table].state_names[get_sm_state(sm_state)].sub_state_names[i] != NULL ; i ++) {
    if(strcmp(sub_state_name, sm_names[sm_curr_table].state_names[get_sm_state(sm_state)].sub_state_names[i]) == 0) {
      printf("sub-state %s -> %s\n",
      sm_names[sm_curr_table].state_names[get_sm_state(sm_state)].sub_state_names[get_sm_ss_state(sm_state)],
      sm_names[sm_curr_table].state_names[get_sm_state(sm_state)].sub_state_names[i]
      );
      sm_set_sub_state(i);
      return 0;
    }
  }
  return 1;
}
